In [1]:
import pandas as pd

df = pd.read_csv('csv/loan_data.csv')

df.head(10)

   age  income  credit_score  existing_loans  employed  default
0   47  151735           616               1         1        0
1   40   72912           781               1         1        0
2   49  152455           568               2         0        0
3   60  120771           654               1         1        1
4   39   86572           767               1         1        0
5   39   49276           695               1         1        0
6   60  137459           790               1         1        0
7   51   55534           537               4         1        0
8   36   65670           674               1         1        0
9   48  112147           806               2         1        0

In [2]:
# Check missing values

print(df.isnull().sum())

# Data types
print(df.dtypes)

age               0
income            0
credit_score      0
existing_loans    0
employed          0
default           0
dtype: int64
age               int64
income            int64
credit_score      int64
existing_loans    int64
employed          int64
default           int64
dtype: object

In [3]:
percent_default = lambda a, b: (a/b)*100

(df["default"].value_counts()[0] / df["default"].count()) *100

np.float64(79.2)

In [4]:
total_defaults = df["default"].value_counts()[0]
total_counts = df["default"].count()
print(total_defaults, total_counts)

print(percent_default(total_defaults, total_counts))

# 79.2 % Loan default hai 
# 100 - 79.2 = 20.8 % logon ne loan repay kiya hai
total_non_defaults = df["default"].value_counts()[1]
print(percent_default(total_non_defaults, total_counts))

3960 5000
79.2
20.8

In [5]:
df["default"].count()

np.int64(5000)

In [6]:
df["default"].value_counts()

default
0    3960
1    1040
Name: count, dtype: int64

In [7]:
(54/100)*100

54.0

In [8]:
import pandas as pd

df = pd.read_csv('csv/loan_data.csv')
df.head()

   age  income  credit_score  existing_loans  employed  default
0   47  151735           616               1         1        0
1   40   72912           781               1         1        0
2   49  152455           568               2         0        0
3   60  120771           654               1         1        1
4   39   86572           767               1         1        0

In [9]:
# People who are not employed but have income
unemployed_with_income = df.loc[(df["employed"]== 0) & (df["income"] > 0)]
unemployed_with_income

      age  income  credit_score  existing_loans  employed  default
2      49  152455           568               2         0        0
30     34   89624           763               1         0        1
65     58  181932           626               3         0        0
67     54  117300           653               0         0        1
75     51  107442           662               0         0        1
...   ...     ...           ...             ...       ...      ...
4970   60  103865           696               1         0        0
4973   25   55191           688               0         0        0
4976   58  198795           695               2         0        1
4987   42   87710           694               4         0        1
4993   48  122358           723               3         0        1

[718 rows x 6 columns]

In [10]:
import numpy as np
len(unemployed_with_income)

718

In [11]:
df.loc[ (df["employed"]==0) & (df["income"]>0) & (df["age"]<60), "income" ] = 2000

In [12]:
df.loc[(df["employed"]==0) & (df["income"]>0) & (df["age"]<60)]

      age  income  credit_score  existing_loans  employed  default
2      49    2000           568               2         0        0
30     34    2000           763               1         0        1
65     58    2000           626               3         0        0
67     54    2000           653               0         0        1
75     51    2000           662               0         0        1
...   ...     ...           ...             ...       ...      ...
4961   29    2000           746               3         0        1
4973   25    2000           688               0         0        0
4976   58    2000           695               2         0        1
4987   42    2000           694               4         0        1
4993   48    2000           723               3         0        1

[663 rows x 6 columns]

In [13]:
df.isna().sum()

age               0
income            0
credit_score      0
existing_loans    0
employed          0
default           0
dtype: int64

In [14]:
import pandas as pd
df = pd.read_csv('csv/copy.csv')
df.head()

   age  income  credit_score  existing_loans  employed  default
0   47  151735           616               1         1        0
1   40   72912           781               1         1        0
2   49  152455           568               2         0        0
3   60  120771           654               1         1        1
4   39   86572           767               1         1        0

In [15]:
len_unemp_with_inc = len(df.loc[(df["employed"]==0) & (df["age"]<60) & (df["income"]>0)])
len_unemp_with_inc

663

In [16]:
import numpy as np

arr = np.random.randint(2000, 6000, size=(len_unemp_with_inc))
arr.size

663

In [17]:
df.loc[(df["employed"]==0) & (df["age"]<60) & (df["income"]>0), "income"] = arr

In [18]:
print("hello world")

hello world

In [19]:
df[df["income"]==2000]

Empty DataFrame
Columns: [age, income, credit_score, existing_loans, employed, default]
Index: []

In [20]:
df.head(100)

    age  income  credit_score  existing_loans  employed  default
0    47  151735           616               1         1        0
1    40   72912           781               1         1        0
2    49    4847           568               2         0        0
3    60  120771           654               1         1        1
4    39   86572           767               1         1        0
..  ...     ...           ...             ...       ...      ...
95   25    5890           770               1         0        1
96   45  139494           679               4         1        0
97   45  117067           794               1         1        0
98   42  121017           706               2         1        0
99   39   53932           842               5         1        0

[100 rows x 6 columns]

In [21]:
import numpy as np
len_retired_ppl = len(df.loc[(df["employed"]==0) & (df["age"]>=60) & (df["income"]>0)])

arr = np.random.randint(15000, 18000, size=len_retired_ppl)

arr.size

55

In [24]:
df.loc[(df["employed"]==0) & (df["age"]>=60) & (df["income"]>0), "income"] = arr

In [55]:
# df.loc[(df["employed"]==0) & (df["age"]<60) & (df["income"]>0)]

df.loc[(df["age"]>=60) & (df["employed"]==0)]

      age  income  credit_score  existing_loans  employed  default
106    64   17883           738               1         0        0
135    60   17402           708               0         0        0
209    70   17747           705               1         0        1
387    64   15973           536               3         0        1
393    63   15982           755               0         0        0
494    60   15576           680               0         0        0
624    61   15527           714               5         0        1
738    61   17219           652               2         0        0
880    70   15507           735               3         0        1
885    64   16922           729               3         0        0
967    63   16891           707               1         0        1
996    63   17035           654               2         0        0
1154   61   16866           812               3         0        0
1157   69   16986           676               3         0        1
1387   60   16844           666               1         0        0
1466   62   15866           623               3         0        0
1496   66   15948           669               0         0        1
1541   63   17831           797               3         0        0
1638   66   15603           725               1         0        1
1897   61   16337           746               2         0        0
1910   62   16568           705               4         0        1
2164   60   15136           824               1         0        0
2311   63   17835           628               2         0        1
2404   62   16737           664               0         0        0
2411   60   15988           784               3         0        1
2506   70   17147           651               3         0        0
2544   70   16636           635               3         0        0
2709   60   17952           621               0         0        0
2724   65   17992           677               1         0        1
2731   62   15024           655               3         0        1
2734   65   16257           743               2         0        0
2814   63   16442           683               1         0        0
2825   62   15219           646               3         0        0
2953   60   16819           575               3         0        0
3192   69   17224           614               1         0        0
3213   60   16449           732               0         0        0
3285   60   16185           495               2         0        1
3296   62   17937           741               3         0        1
3394   65   17703           715               5         0        1
3409   66   16858           798               1         0        1
3534   67   16572           618               3         0        0
3580   67   17217           719               3         0        0
3582   65   16772           658               4         0        0
3602   66   15387           830               3         0        1
3686   70   16674           667               4         0        0
3920   64   15704           621               5         0        1
3982   70   15078           800               3         0        0
3998   61   17556           706               1         0        1
4114   61   17291           630               3         0        0
4129   61   15947           798               0         0        0
4226   64   17853           712               1         0        1
4495   62   17697           628               3         0        1
4621   62   16234           706               1         0        0
4655   67   16533           816               2         0        0
4970   60   15834           696               1         0        0