In [1]:
print("Hello World")

Hello World

## Date :- 2026-04-22

In [2]:
import pandas as pd
import numpy as np

In [3]:
FILE_PATH = "csv/copy.csv"

In [4]:
df = pd.read_csv(FILE_PATH)

In [5]:
df.head()

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,18703,616,1,1,0,0.0,36
1,40,16169,781,1,1,0,0.0,36
2,49,14477,568,2,0,0,0.0,36
3,60,14922,654,1,1,1,0.0,36
4,39,15606,767,1,1,0,0.0,36

In [6]:
df[df["loan_amount"]==0]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,18703,616,1,1,0,0.0,36
1,40,16169,781,1,1,0,0.0,36
2,49,14477,568,2,0,0,0.0,36
3,60,14922,654,1,1,1,0.0,36
4,39,15606,767,1,1,0,0.0,36
...,...,...,...,...,...,...,...,...
4993,48,19630,723,3,0,1,0.0,36
4994,34,19383,839,1,1,0,0.0,36
4996,50,18314,768,3,1,0,0.0,36
4998,51,17608,638,0,1,0,0.0,36
4999,31,18223,674,1,1,0,0.0,36

In [7]:
df.loc[
    (df["age"]>=70) &
    (df["employed"]==1)
].shape

(39, 8)

In [8]:
unemployed = (df["employed"]==0) & \
(df["loan_amount"]==0)

In [9]:
df[unemployed]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
2,49,14477,568,2,0,0,0.0,36
30,34,17060,763,1,0,1,0.0,36
65,58,16334,626,3,0,0,0.0,36
83,35,19649,724,0,0,0,0.0,36
95,25,12044,770,1,0,1,0.0,36
...,...,...,...,...,...,...,...,...
4958,41,12199,618,1,0,0,0.0,36
4961,29,12646,746,3,0,1,0.0,36
4973,25,12402,688,0,0,0,0.0,36
4987,42,13410,694,4,0,1,0.0,36
4993,48,19630,723,3,0,1,0.0,36

In [10]:
unemp_oldage = unemployed & \
(df["age"]>=60)

In [11]:
df[unemp_oldage].shape

(31, 8)

In [12]:
df[unemp_oldage]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
393,63,16279,755,0,0,0,0.0,36
624,61,12291,714,5,0,1,0.0,36
880,70,16940,735,3,0,1,0.0,36
885,64,15378,729,3,0,0,0.0,36
1154,61,15135,812,3,0,0,0.0,36
1157,69,15651,676,3,0,1,0.0,36
1466,62,14686,623,3,0,0,0.0,36
1541,63,19739,797,3,0,0,0.0,36
1910,62,18038,705,4,0,1,0.0,36
2164,60,14927,824,1,0,0,0.0,36
2411,60,19068,784,3,0,1,0.0,36
2506,70,18745,651,3,0,0,0.0,36
2544,70,13296,635,3,0,0,0.0,36
2731,62,19777,655,3,0,1,0.0,36
2825,62,15435,646,3,0,0,0.0,36
2953,60,19629,575,3,0,0,0.0,36
3285,60,15805,495,2,0,1,0.0,36
3296,62,15114,741,3,0,1,0.0,36
3394,65,13832,715,5,0,1,0.0,36
3409,66,15276,798,1,0,1,0.0,36
3534,67,18448,618,3,0,0,0.0,36
3580,67,17454,719,3,0,0,0.0,36
3582,65,18887,658,4,0,0,0.0,36
3602,66,12119,830,3,0,1,0.0,36
3686,70,13529,667,4,0,0,0.0,36
3920,64,17569,621,5,0,1,0.0,36
3982,70,18897,800,3,0,0,0.0,36
4114,61,14921,630,3,0,0,0.0,36
4129,61,12660,798,0,0,0,0.0,36
4495,62,18691,628,3,0,1,0.0,36
4655,67,13700,816,2,0,0,0.0,36

In [13]:
df.loc[unemp_oldage.index, 'income']

0       18703
1       16169
2       14477
3       14922
4       15606
        ...
4995    15236
4996    18314
4997    17273
4998    17608
4999    18223
Name: income, Length: 5000, dtype: int64

In [14]:
# # Pension assign karo
# df.loc[unemp_oldage.index, 'income'] = np.random.randint(12000, 20000, size=unemp_oldage.shape[0])

# print(f"Pension assigned to {unemp_oldage.shape[0]} persons")

In [26]:
df[unemp_oldage].shape

(31, 8)

In [16]:
unemp_young = unemployed & \
(df["age"]<60)

In [55]:
df.loc[
    unemp_young &
    (df["income"]<20000)
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
2,49,14477,568,2,0,0,0.0,36
30,34,17060,763,1,0,1,0.0,36
65,58,16334,626,3,0,0,0.0,36
83,35,19649,724,0,0,0,0.0,36
95,25,12044,770,1,0,1,0.0,36
...,...,...,...,...,...,...,...,...
4958,41,12199,618,1,0,0,0.0,36
4961,29,12646,746,3,0,1,0.0,36
4973,25,12402,688,0,0,0,0.0,36
4987,42,13410,694,4,0,1,0.0,36
4993,48,19630,723,3,0,1,0.0,36

In [18]:
print(df[unemp_young]['credit_score'].describe())

count    485.000000
mean     713.490722
std       83.541661
min      471.000000
25%      653.000000
50%      718.000000
75%      772.000000
max      900.000000
Name: credit_score, dtype: float64

In [19]:
df.to_csv(FILE_PATH, index=False)

In [20]:
df.loc[(df["loan_amount"]==0)]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,18703,616,1,1,0,0.0,36
1,40,16169,781,1,1,0,0.0,36
2,49,14477,568,2,0,0,0.0,36
3,60,14922,654,1,1,1,0.0,36
4,39,15606,767,1,1,0,0.0,36
...,...,...,...,...,...,...,...,...
4993,48,19630,723,3,0,1,0.0,36
4994,34,19383,839,1,1,0,0.0,36
4996,50,18314,768,3,1,0,0.0,36
4998,51,17608,638,0,1,0,0.0,36
4999,31,18223,674,1,1,0,0.0,36

In [41]:
import pandas as pd
import numpy as np
FILE_PATH = "csv/copy.csv"
df = pd.read_csv(FILE_PATH)

In [42]:
df.head()

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,18703,616,1,1,0,0.0,36
1,40,16169,781,1,1,0,0.0,36
2,49,14477,568,2,0,0,0.0,36
3,60,14922,654,1,1,1,0.0,36
4,39,15606,767,1,1,0,0.0,36

In [43]:
df[df["loan_amount"]==0].shape

(3882, 8)

In [47]:
df[unemp_oldage].shape[0]

31

In [51]:
# Minimum 80k-100k guarantee
df.loc[unemp_oldage, 'loan_amount'] = np.round(
    np.random.randint(80000, 100000, size=df[unemp_oldage].shape[0])
)

# df.loc[unemp_oldage.index, 'loan_amount'] = df.loc[unemp_oldage.index, 'loan_amount'].astype(int)

print(f"Loan assigned: {df[unemp_oldage].shape[0]} rows")

Loan assigned: 31 rows

In [52]:
df.loc[
    (df["loan_amount"]==0)&
    (df["employed"]==0)
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
2,49,14477,568,2,0,0,0.0,36
30,34,17060,763,1,0,1,0.0,36
65,58,16334,626,3,0,0,0.0,36
83,35,19649,724,0,0,0,0.0,36
95,25,12044,770,1,0,1,0.0,36
...,...,...,...,...,...,...,...,...
4958,41,12199,618,1,0,0,0.0,36
4961,29,12646,746,3,0,1,0.0,36
4973,25,12402,688,0,0,0,0.0,36
4987,42,13410,694,4,0,1,0.0,36
4993,48,19630,723,3,0,1,0.0,36

In [45]:
un= (df["employed"]==0)

In [53]:
df.loc[
    
    (df["loan_amount"]>0)
].shape

(1149, 8)

In [54]:
df[unemp_young].shape

(485, 8)

In [57]:
high_cib = unemp_young & (df["credit_score"]>=700)

In [59]:
mid_cib = unemp_young & (df["credit_score"].between(550, 699))

In [61]:
low_cib = unemp_young & (df["credit_score"]<550)

In [63]:
df[low_cib].shape

(13, 8)

In [64]:
high_cib.shape

(5000,)

In [66]:
# High credit
df.loc[high_cib, 'loan_amount'] = df.loc[high_cib, 'income'] * 3 * \
                                         np.round(np.random.uniform(0.9, 1.1, size=df[high_cib].shape[0]))

In [67]:
# Mid credit
df.loc[mid_cib, 'loan_amount'] = df.loc[mid_cib, 'income'] * 2 * \
                                        np.round(np.random.uniform(0.9, 1.1, size=df[mid_cib].shape[0]))

In [68]:
# Low credit
df.loc[low_cib, 'loan_amount'] = df.loc[low_cib, 'income'] * 1.5 * \
                                        np.round(np.random.uniform(0.9, 1.1, size=df[low_cib].shape[0]))

In [69]:
df.loc[unemp_young.index, 'loan_amount'] = df.loc[unemp_young.index, 'loan_amount'].astype(int)

print(f"unemp_young loan assigned!")

unemp_young loan assigned!

In [92]:
df.loc[
    unemp_young &
    df["loan_amount"]>0
].shape

(485, 8)

In [84]:
# 60+ unemployed (unemp_oldage)
# high_cib_old = unemp_oldage[unemp_oldage['credit_score'] > 700]
high_cib_old = unemp_oldage & (df['credit_score'] > 700)

mid_cib_old = unemp_oldage & (df['credit_score'].between(550, 700))
low_cib_old = unemp_oldage & (df['credit_score']<550)

In [83]:
df[low_cib_old].shape

(1, 8)

In [85]:
# High credit
df.loc[high_cib_old, 'loan_amount'] = np.maximum(
    df.loc[high_cib_old, 'income'] * 5 * np.round(np.random.uniform(0.9, 1.1, size=df[high_cib_old].shape[0])),
    np.random.randint(90000, 100000, size=df[high_cib_old].shape[0])
)

In [86]:
# Mid credit
df.loc[mid_cib_old, 'loan_amount'] = np.maximum(
    df.loc[mid_cib_old, 'income'] * 4 * np.round(np.random.uniform(0.9, 1.1, size=df[mid_cib_old].shape[0])),
    np.random.randint(70000, 80000, size=df[mid_cib_old].shape[0])
)

In [87]:
# Low credit
df.loc[low_cib_old, 'loan_amount'] = np.maximum(
    df.loc[low_cib_old, 'income'] * 3 * np.round(np.random.uniform(0.9, 1.1, size=df[low_cib_old].shape[0])),
    np.random.randint(50000, 60000, size=df[low_cib_old].shape[0])
)

In [ ]:
df.loc[unemp_oldage.index, 'loan_amount'] = df.loc[unemp_oldage.index, 'loan_amount'].astype(int)

print("60+ credit-based loan assigned!")

In [91]:
df.loc[
    unemp_oldage & 
    (df["loan_amount"]>0)
].shape

(0, 8)

In [95]:
df.loc[
    (df["loan_amount"]==0)
].shape

(3366, 8)

In [99]:
emp = (df["employed"]==1)

In [103]:
unemp = (df["employed"]==0)

In [108]:
old_age = (df["age"]>=60)
young_age = (df["age"]<60)

In [109]:
high_c = (df["credit_score"]>700)
mid_c  = (df["credit_score"].between(550, 700))
low_c  = (df["credit_score"]<550)

In [110]:
df[high_c].shape

(2443, 8)

In [135]:
un_assigned = (df["loan_amount"]==0)
assigned = (df["loan_amount"]>0)

In [145]:
df.loc[
    assigned &
    emp & old_age & high_c
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
6,60,15257,790,1,1,0,0.0,36
71,60,13204,770,1,1,0,0.0,36
73,60,13120,789,3,1,0,0.0,36
113,70,13211,779,5,1,1,0.0,36
125,68,12007,805,1,1,0,0.0,36
...,...,...,...,...,...,...,...,...
4667,61,14903,720,2,1,1,0.0,36
4784,70,15840,765,2,1,0,0.0,36
4870,70,19475,724,5,1,0,0.0,36
4985,61,18109,735,2,1,0,0.0,36
4997,70,17273,788,2,1,0,0.0,36

In [139]:
df[assigned & emp & old_age & high_c].shape[0]

137

In [124]:
# Assigning loan to Employed Old Aged

In [128]:
# Old age high credit
df.loc[un_assigned & emp & old_age & high_c, 'loan_amount'] = df.loc[un_assigned & emp & old_age & high_c, 'income'] * 7 * \
                                                 np.round(np.random.uniform(0.9, 1.1, size=df[un_assigned & emp & old_age & high_c].shape[0]))

In [144]:
# Old age high credit
df.loc[assigned & emp & old_age & high_c, 'loan_amount'] = 0

In [149]:
df[un_assigned].shape

(3263, 8)

In [156]:
df.loc[
    un_assigned & emp & old_age &
    (df["income"]<=19999)
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
3,60,14922,654,1,1,1,0.0,36
31,64,14993,680,5,1,0,0.0,36
156,64,18434,614,2,1,0,0.0,36
179,70,14555,674,1,1,0,0.0,36
252,67,16444,689,1,1,0,0.0,36
...,...,...,...,...,...,...,...,...
4887,61,15969,602,2,1,0,0.0,36
4920,61,14792,675,1,1,0,0.0,36
4932,60,14493,700,1,1,0,0.0,36
4944,62,14941,581,0,1,0,0.0,36
4989,70,16922,698,1,1,0,0.0,36

In [161]:
df.loc[
    (df["income"]>50000)
    
    ]

Empty DataFrame
Columns: [age, income, credit_score, existing_loans, employed, default, loan_amount, loan_tenure_months]
Index: []

In [162]:
df[df["income"]>50000]

Empty DataFrame
Columns: [age, income, credit_score, existing_loans, employed, default, loan_amount, loan_tenure_months]
Index: []

In [163]:
print(df.shape[0])  # Total rows check kar
print(df['loan_amount'].isna().sum())  # Null loans
print(df[df['loan_amount'] == 0].shape[0])  # Zero loans

5000
0
3400

In [168]:
df.loc[
    (df["loan_amount"]>900000)
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
122,58,16414,770,5,1,0,1066288.0,36
141,57,17346,807,3,1,0,1027824.0,36
316,50,16129,818,5,1,0,1200200.0,36
373,53,13757,785,1,1,0,1197336.0,36
388,53,15329,787,2,1,0,1269472.0,36
...,...,...,...,...,...,...,...,...
4786,50,18822,816,2,1,0,960072.0,36
4838,58,18458,778,2,1,0,1579760.0,36
4856,52,17910,753,0,1,0,1210488.0,36
4937,56,13729,776,2,1,0,1156096.0,36
4957,54,19265,771,0,1,0,1133656.0,36

In [169]:
df.to_csv(FILE_PATH, index=False)

In [170]:
df=pd.read_csv(FILE_PATH)

In [171]:
df.loc[
    (df["loan_amount"]>900000)
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
122,58,16414,770,5,1,0,1066288.0,36
141,57,17346,807,3,1,0,1027824.0,36
316,50,16129,818,5,1,0,1200200.0,36
373,53,13757,785,1,1,0,1197336.0,36
388,53,15329,787,2,1,0,1269472.0,36
...,...,...,...,...,...,...,...,...
4786,50,18822,816,2,1,0,960072.0,36
4838,58,18458,778,2,1,0,1579760.0,36
4856,52,17910,753,0,1,0,1210488.0,36
4937,56,13729,776,2,1,0,1156096.0,36
4957,54,19265,771,0,1,0,1133656.0,36