In [1]:
print("Hello World")

Hello World

In [9]:
import pandas as pd
import numpy as np
FILE_PATH = "csv-2/copy.csv"
df = pd.read_csv(FILE_PATH)

In [10]:
df = pd.read_csv(FILE_PATH)

In [11]:
df.head()

,age,income,credit_score,existing_loans,existing_loan_emi,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,0,1,0,632304,24
1,40,69517,781,1,0,1,0,417102,12
2,49,28572,568,2,0,0,0,83408,12
3,60,71067,654,1,0,1,1,284268,24
4,39,68930,767,1,0,1,0,482510,12

In [21]:
df.to_csv(FILE_PATH, index=False)

In [27]:
df.head()

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,632304,24
1,40,69517,781,1,1,0,417102,12
2,49,28572,568,2,0,0,83408,12
3,60,71067,654,1,1,1,284268,24
4,39,68930,767,1,1,0,482510,12

In [5]:
df.head()

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,632304,24
1,40,69517,781,1,1,0,417102,12
2,49,28572,568,2,0,0,83408,12
3,60,71067,654,1,1,1,284268,24
4,39,68930,767,1,1,0,482510,12

In [12]:
df["existing_loan_emi"] = 0

In [7]:
df.head()

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months,existing_loan_emi
0,47,105384,616,1,1,0,632304,24,0
1,40,69517,781,1,1,0,417102,12,0
2,49,28572,568,2,0,0,83408,12,0
3,60,71067,654,1,1,1,284268,24,0
4,39,68930,767,1,1,0,482510,12,0

In [9]:
df = df[["age", "income", "credit_score", "existing_loans", "existing_loan_emi", "employed",
   "default", "loan_amount", "loan_tenure_months"
   ]]

In [13]:
df.to_csv(FILE_PATH, index=False)

In [14]:
df.head()

,age,income,credit_score,existing_loans,existing_loan_emi,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,0,1,0,632304,24
1,40,69517,781,1,0,1,0,417102,12
2,49,28572,568,2,0,0,0,83408,12
3,60,71067,654,1,0,1,1,284268,24
4,39,68930,767,1,0,1,0,482510,12

In [14]:
# Adding new columns

df["employement_type"] = None

In [15]:
df.head()

,age,income,credit_score,existing_loans,existing_loan_emi,employed,default,loan_amount,loan_tenure_months,employement_type
0,47,105384,616,1,0,1,0,632304,24,None
1,40,69517,781,1,0,1,0,417102,12,None
2,49,28572,568,2,0,0,0,83408,12,None
3,60,71067,654,1,0,1,1,284268,24,None
4,39,68930,767,1,0,1,0,482510,12,None

In [16]:
df[["emi_to_income_ratio", "loan_to_income_ratio"]] = 0

In [17]:
df.head()

,age,income,credit_score,existing_loans,existing_loan_emi,employed,default,loan_amount,loan_tenure_months,employement_type,emi_to_income_ratio,loan_to_income_ratio
0,47,105384,616,1,0,1,0,632304,24,None,0,0
1,40,69517,781,1,0,1,0,417102,12,None,0,0
2,49,28572,568,2,0,0,0,83408,12,None,0,0
3,60,71067,654,1,0,1,1,284268,24,None,0,0
4,39,68930,767,1,0,1,0,482510,12,None,0,0

In [ ]:
import pandas as pd
import numpy as np
FILE_PATH = "csv-2/copy.csv"
df = pd.read_csv(FILE_PATH)