In [1]:
print("Hello World")

Hello World

In [2]:
import pandas as pd
import numpy as np
FILE = "csv-2/copy.csv"
df = pd.read_csv(FILE)

In [3]:
df.head()

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,0,36
1,40,69517,781,1,1,0,0,36
2,49,28572,568,2,0,0,83408,36
3,60,71067,654,1,1,1,0,36
4,39,68930,767,1,1,0,0,36

## Assigning Loans to EMPLOYED people

In [4]:
## Worst Cibil 

worst_emp = (df['employed'] == 1) & (df['credit_score'] < 400)

In [18]:
worst_emp = (df['employed'] == 1) & (df['credit_score'] < 400)


df.loc[(worst_emp) & (df['age'].between(30, 40)), 'loan_amount'] = \
    df.loc[(worst_emp) & (df['age'].between(30, 40)), 'income'] * np.random.randint(4, 6, size=df[(worst_emp) & (df['age'].between(30, 40))].shape[0])

df.loc[(worst_emp) & (df['age'].between(41, 55)), 'loan_amount'] = \
    np.maximum(df.loc[(worst_emp) & (df['age'].between(41, 55)), 'income'] * np.random.randint(4, 6, size=df[(worst_emp) & (df['age'].between(41, 55))].shape[0]), 500000)



df.loc[worst_emp, 'loan_amount'] = df.loc[worst_emp, 'loan_amount'].astype(int)

print(f"Employed worst credit loans assigned! {worst_emp.sum()} rows now")

Employed worst credit loans assigned! 2 rows now

In [19]:
df[worst_emp]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
1507,53,109011,399,3,1,1,545055,36
1561,33,53733,375,1,1,0,214932,36

In [20]:
## POOR cibil 
poor_emp = (df['employed'] == 1) & (df['credit_score'].between(401, 550))

In [22]:

df.loc[(poor_emp) & (df['age'].between(25, 29)), 'loan_amount'] = \
    df.loc[(poor_emp) & (df['age'].between(25, 29)), 'income'] * np.random.randint(5, 7, size=df[(poor_emp) & (df['age'].between(25, 29))].shape[0])

df.loc[(poor_emp) & (df['age'].between(30, 40)), 'loan_amount'] = \
    df.loc[(poor_emp) & (df['age'].between(30, 40)), 'income'] * np.random.randint(5, 7, size=df[(poor_emp) & (df['age'].between(30, 40))].shape[0])

df.loc[(poor_emp) & (df['age'].between(41, 55)), 'loan_amount'] = \
    df.loc[(poor_emp) & (df['age'].between(41, 55)), 'income'] * np.random.randint(5, 7, size=df[(poor_emp) & (df['age'].between(41, 55))].shape[0])

df.loc[(poor_emp) & (df['age'].between(56, 59)), 'loan_amount'] = \
    df.loc[(poor_emp) & (df['age'].between(56, 59)), 'income'] * np.random.randint(5, 7, size=df[(poor_emp) & (df['age'].between(56, 59))].shape[0])

df.loc[(poor_emp) & (df['age'] >= 60), 'loan_amount'] = \
    df.loc[(poor_emp) & (df['age'] >= 60), 'income'] * np.random.randint(3, 5, size=df[(poor_emp) & (df['age'] >= 60)].shape[0])

df.loc[poor_emp, 'loan_amount'] = df.loc[poor_emp, 'loan_amount'].astype(int)

print(f"Employed poor credit loans assigned! {poor_emp.sum()} rows")

Employed poor credit loans assigned! 141 rows

In [23]:
df[poor_emp]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
7,51,117736,537,4,1,0,588680,36
54,54,151874,510,5,1,1,759370,36
89,48,118310,543,0,1,0,709860,36
202,54,104257,484,2,1,0,625542,36
226,42,67869,500,1,1,0,339345,36
...,...,...,...,...,...,...,...,...
4722,42,65760,509,0,1,0,328800,36
4774,25,30600,517,3,1,0,183600,36
4948,37,79987,486,3,1,0,479922,36
4953,53,152259,544,1,1,0,913554,36
4960,38,65380,516,1,1,0,392280,36

In [24]:
## GOOD cibil 
good_emp = (df['employed'] == 1) & (df['credit_score'].between(551, 699))

In [26]:

df.loc[(good_emp) & (df['age'].between(25, 29)), 'loan_amount'] = \
    df.loc[(good_emp) & (df['age'].between(25, 29)), 'income'] * np.random.randint(5, 8, size=df[(good_emp) & (df['age'].between(25, 29))].shape[0])

df.loc[(good_emp) & (df['age'].between(30, 40)), 'loan_amount'] = \
    df.loc[(good_emp) & (df['age'].between(30, 40)), 'income'] * np.random.randint(5, 8, size=df[(good_emp) & (df['age'].between(30, 40))].shape[0])

df.loc[(good_emp) & (df['age'].between(41, 55)), 'loan_amount'] = \
    df.loc[(good_emp) & (df['age'].between(41, 55)), 'income'] * np.random.randint(5, 8, size=df[(good_emp) & (df['age'].between(41, 55))].shape[0])

df.loc[(good_emp) & (df['age'].between(56, 59)), 'loan_amount'] = \
    df.loc[(good_emp) & (df['age'].between(56, 59)), 'income'] * np.random.randint(5, 8, size=df[(good_emp) & (df['age'].between(56, 59))].shape[0])

df.loc[(good_emp) & (df['age'] >= 60), 'loan_amount'] = \
    df.loc[(good_emp) & (df['age'] >= 60), 'income'] * np.random.randint(4, 6, size=df[(good_emp) & (df['age'] >= 60)].shape[0])

df.loc[good_emp, 'loan_amount'] = df.loc[good_emp, 'loan_amount'].astype(int)

print(f"Employed good credit loans assigned! {good_emp.sum()} rows")

Employed good credit loans assigned! 2023 rows

In [27]:
df[good_emp]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,526920,36
3,60,71067,654,1,1,1,284268,36
5,39,67947,695,1,1,0,475629,36
8,36,68281,674,1,1,0,341405,36
10,36,76048,609,2,1,0,380240,36
...,...,...,...,...,...,...,...,...
4990,25,30843,667,2,1,0,215901,36
4991,50,152453,651,1,1,0,762265,36
4992,40,84042,693,1,1,1,420210,36
4998,51,166975,638,0,1,0,834875,36
4999,31,48188,674,1,1,0,289128,36

In [28]:
## BEST cibil 
best_emp = (df['employed'] == 1) & (df['credit_score'] >= 700)

In [30]:

df.loc[(best_emp) & (df['age'].between(25, 29)), 'loan_amount'] = \
    df.loc[(best_emp) & (df['age'].between(25, 29)), 'income'] * np.random.randint(6, 9, size=df[(best_emp) & (df['age'].between(25, 29))].shape[0])

df.loc[(best_emp) & (df['age'].between(30, 40)), 'loan_amount'] = \
    df.loc[(best_emp) & (df['age'].between(30, 40)), 'income'] * np.random.randint(6, 9, size=df[(best_emp) & (df['age'].between(30, 40))].shape[0])

df.loc[(best_emp) & (df['age'].between(41, 55)), 'loan_amount'] = \
    df.loc[(best_emp) & (df['age'].between(41, 55)), 'income'] * np.random.randint(6, 9, size=df[(best_emp) & (df['age'].between(41, 55))].shape[0])

df.loc[(best_emp) & (df['age'].between(56, 59)), 'loan_amount'] = \
    df.loc[(best_emp) & (df['age'].between(56, 59)), 'income'] * np.random.randint(6, 9, size=df[(best_emp) & (df['age'].between(56, 59))].shape[0])

df.loc[(best_emp) & (df['age'] >= 60), 'loan_amount'] = \
    df.loc[(best_emp) & (df['age'] >= 60), 'income'] * np.random.randint(5, 7, size=df[(best_emp) & (df['age'] >= 60)].shape[0])

df.loc[best_emp, 'loan_amount'] = df.loc[best_emp, 'loan_amount'].astype(int)

print(f"Employed best credit loans assigned! {best_emp.sum()} rows")

Employed best credit loans assigned! 2116 rows

In [31]:
df[best_emp]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
1,40,69517,781,1,1,0,417102,36
4,39,68930,767,1,1,0,413580,36
6,60,73017,790,1,1,0,365085,36
9,48,149422,806,2,1,0,896532,36
11,36,66951,782,1,1,0,401706,36
...,...,...,...,...,...,...,...,...
4985,61,73889,735,2,1,0,369445,36
4994,34,50808,839,1,1,0,304848,36
4995,41,69736,745,2,1,0,557888,36
4996,50,103089,768,3,1,0,721623,36
4997,70,89423,788,2,1,0,536538,36

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,526920,36
1,40,69517,781,1,1,0,417102,36
2,49,28572,568,2,0,0,83408,36
3,60,71067,654,1,1,1,284268,36
4,39,68930,767,1,1,0,413580,36
...,...,...,...,...,...,...,...,...
4995,41,69736,745,2,1,0,557888,36
4996,50,103089,768,3,1,0,721623,36
4997,70,89423,788,2,1,0,536538,36
4998,51,166975,638,0,1,0,834875,36
4999,31,48188,674,1,1,0,289128,36

In [38]:
# Safe point

df.to_csv(FILE, index=False)

In [50]:
import pandas as pd
df = pd.read_csv(FILE)
df.head()

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,526920,36
1,40,69517,781,1,1,0,417102,36
2,49,28572,568,2,0,0,83408,36
3,60,71067,654,1,1,1,284268,36
4,39,68930,767,1,1,0,413580,36

In [40]:
df.loc[
    (df["loan_amount"]>0)
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,526920,36
1,40,69517,781,1,1,0,417102,36
2,49,28572,568,2,0,0,83408,36
3,60,71067,654,1,1,1,284268,36
4,39,68930,767,1,1,0,413580,36
...,...,...,...,...,...,...,...,...
4995,41,69736,745,2,1,0,557888,36
4996,50,103089,768,3,1,0,721623,36
4997,70,89423,788,2,1,0,536538,36
4998,51,166975,638,0,1,0,834875,36
4999,31,48188,674,1,1,0,289128,36

### Adding new rows for unemployed persons with worst credit score

In [52]:
import numpy as np

# Create 213 rows
new_rows_unemp = 263

new_data_unemp = {
    'age': np.random.randint(25, 71, size=new_rows_unemp),
    'income': 0,
    'credit_score': np.random.randint(300, 401, size=new_rows_unemp),
    'existing_loans': np.random.randint(0, 4, size=new_rows_unemp),
    'employed': 0,
    'default': 0,
    'loan_amount': 0,
    'loan_tenure_months': 36
}

new_df_unemp = pd.DataFrame(new_data_unemp)

# Append to main df
df = pd.concat([df, new_df_unemp], ignore_index=True)

print(f"Added {new_rows_unemp} unemployed worst credit rows!")
print(f"Total rows now: {df.shape[0]}")

Added 263 unemployed worst credit rows!
Total rows now: 5263

In [48]:
df.loc[
    (df["loan_amount"]==0)
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5000,70,0,312,3,0,0,0,36
5001,66,0,323,1,0,0,0,36
5002,40,0,338,0,0,0,0,36
5003,69,0,364,2,0,0,0,36
5004,53,0,321,2,0,0,0,36
...,...,...,...,...,...,...,...,...
5661,43,0,315,0,0,0,0,36
5662,48,0,340,2,0,0,0,36
5663,39,0,322,2,0,0,0,36
5664,25,0,393,2,0,0,0,36
5665,64,0,375,1,0,0,0,36

In [54]:
# Create 190 rows
new_rows_emp = 270

new_data_emp = {
    'age': np.random.randint(25, 71, size=new_rows_emp),
    'income': 0,
    'credit_score': np.random.randint(300, 401, size=new_rows_emp),
    'existing_loans': np.random.randint(0, 4, size=new_rows_emp),
    'employed': 1,
    'default': 0,
    'loan_amount': 0,
    'loan_tenure_months': 36
}

new_df_emp = pd.DataFrame(new_data_emp)

# Append to main df
df = pd.concat([df, new_df_emp], ignore_index=True)

print(f"Added {new_rows_emp} employed worst credit rows!")
print(f"Total rows now: {df.shape[0]}")

Added 270 employed worst credit rows!
Total rows now: 5533

In [55]:
df.shape

(5533, 8)

In [56]:
df.loc[
    (df["employed"]==1) &
    (df["loan_amount"]==0)
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5263,70,0,361,2,1,0,0,36
5264,68,0,341,0,1,0,0,36
5265,43,0,332,2,1,0,0,36
5266,37,0,325,0,1,0,0,36
5267,45,0,330,2,1,0,0,36
...,...,...,...,...,...,...,...,...
5528,66,0,392,2,1,0,0,36
5529,44,0,400,2,1,0,0,36
5530,50,0,399,0,1,0,0,36
5531,33,0,341,0,1,0,0,36
5532,38,0,333,2,1,0,0,36

In [57]:
df.loc[
    (df["employed"]==0) &
    (df["loan_amount"]==0)
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5000,32,0,363,3,0,0,0,36
5001,70,0,334,0,0,0,0,36
5002,53,0,400,3,0,0,0,36
5003,26,0,342,3,0,0,0,36
5004,52,0,345,3,0,0,0,36
...,...,...,...,...,...,...,...,...
5258,30,0,326,0,0,0,0,36
5259,60,0,314,0,0,0,0,36
5260,28,0,324,1,0,0,0,36
5261,27,0,368,3,0,0,0,36
5262,36,0,324,1,0,0,0,36

In [58]:
# Safe point 

df.to_csv(FILE, index=False)

In [59]:
new_unemp = (df['employed'] == 0) & (df['income'] == 0)

In [60]:
df[new_unemp]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5000,32,0,363,3,0,0,0,36
5001,70,0,334,0,0,0,0,36
5002,53,0,400,3,0,0,0,36
5003,26,0,342,3,0,0,0,36
5004,52,0,345,3,0,0,0,36
...,...,...,...,...,...,...,...,...
5258,30,0,326,0,0,0,0,36
5259,60,0,314,0,0,0,0,36
5260,28,0,324,1,0,0,0,36
5261,27,0,368,3,0,0,0,36
5262,36,0,324,1,0,0,0,36

In [61]:

df.loc[(new_unemp) & (df['age'].between(25, 30)), 'income'] = \
    np.random.randint(10000, 18000, size=df[(new_unemp) & (df['age'].between(25, 30))].shape[0])

df.loc[(new_unemp) & (df['age'].between(31, 35)), 'income'] = \
    np.random.randint(15000, 25000, size=df[(new_unemp) & (df['age'].between(31, 35))].shape[0])

df.loc[(new_unemp) & (df['age'].between(36, 45)), 'income'] = \
    np.random.randint(26000, 28000, size=df[(new_unemp) & (df['age'].between(36, 45))].shape[0])

df.loc[(new_unemp) & (df['age'].between(46, 55)), 'income'] = \
    np.random.randint(28000, 30000, size=df[(new_unemp) & (df['age'].between(46, 55))].shape[0])

df.loc[(new_unemp) & (df['age'].between(56, 59)), 'income'] = \
    np.random.randint(20000, 22000, size=df[(new_unemp) & (df['age'].between(56, 59))].shape[0])

df.loc[(new_unemp) & (df['age'] >= 60), 'income'] = \
    np.random.randint(8000, 15000, size=df[(new_unemp) & (df['age'] >= 60)].shape[0])

print(f"Income assigned to {new_unemp.sum()} unemployed rows!")

Income assigned to 263 unemployed rows!

In [69]:
df[new_unemp]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5000,32,21932,363,3,0,0,87728,36
5001,70,11157,334,0,0,0,44628,36
5002,53,29859,400,3,0,0,0,36
5003,26,10918,342,3,0,0,43672,36
5004,52,29225,345,3,0,0,146125,36
...,...,...,...,...,...,...,...,...
5258,30,14833,326,0,0,0,74165,36
5259,60,14347,314,0,0,0,43041,36
5260,28,15592,324,1,0,0,62368,36
5261,27,17727,368,3,0,0,70908,36
5262,36,26565,324,1,0,0,106260,36

In [65]:

df.loc[(new_emp) & (df['age'].between(25, 28)), 'income'] = \
    np.random.randint(20000, 35000, size=df[(new_emp) & (df['age'].between(25, 28))].shape[0])

df.loc[(new_emp) & (df['age'].between(29, 30)), 'income'] = \
    np.random.randint(33000, 40000, size=df[(new_emp) & (df['age'].between(29, 30))].shape[0])

df.loc[(new_emp) & (df['age'].between(31, 35)), 'income'] = \
    np.random.randint(45000, 63000, size=df[(new_emp) & (df['age'].between(31, 35))].shape[0])

df.loc[(new_emp) & (df['age'].between(36, 45)), 'income'] = \
    np.random.randint(65000, 85000, size=df[(new_emp) & (df['age'].between(36, 45))].shape[0])

df.loc[(new_emp) & (df['age'].between(46, 55)), 'income'] = \
    np.random.randint(100000, 180000, size=df[(new_emp) & (df['age'].between(46, 55))].shape[0])

df.loc[(new_emp) & (df['age'].between(56, 59)), 'income'] = \
    np.random.randint(100000, 140000, size=df[(new_emp) & (df['age'].between(56, 59))].shape[0])

df.loc[(new_emp) & (df['age'] >= 60), 'income'] = \
    np.random.randint(70000, 100000, size=df[(new_emp) & (df['age'] >= 60)].shape[0])

print(f"Income assigned to {new_emp.sum()} employed rows!")

Income assigned to 270 employed rows!

In [66]:
df[new_emp]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5263,70,85959,361,2,1,0,0,36
5264,68,93605,341,0,1,0,0,36
5265,43,74005,332,2,1,0,0,36
5266,37,82908,325,0,1,0,0,36
5267,45,80298,330,2,1,0,0,36
...,...,...,...,...,...,...,...,...
5528,66,96365,392,2,1,0,0,36
5529,44,80276,400,2,1,0,0,36
5530,50,173586,399,0,1,0,0,36
5531,33,56839,341,0,1,0,0,36
5532,38,70482,333,2,1,0,0,36

In [67]:
# Unemployed worst cibil 

new_unemp_loans = (df['employed'] == 0) & (df['loan_amount'] == 0) & (df['credit_score'] < 400)

df.loc[(new_unemp_loans) & (df['age'].between(25, 29)), 'loan_amount'] = \
    df.loc[(new_unemp_loans) & (df['age'].between(25, 29)), 'income'] * np.random.randint(4, 6, size=df[(new_unemp_loans) & (df['age'].between(25, 29))].shape[0])

df.loc[(new_unemp_loans) & (df['age'].between(30, 40)), 'loan_amount'] = \
    df.loc[(new_unemp_loans) & (df['age'].between(30, 40)), 'income'] * np.random.randint(4, 6, size=df[(new_unemp_loans) & (df['age'].between(30, 40))].shape[0])

df.loc[(new_unemp_loans) & (df['age'].between(41, 55)), 'loan_amount'] = \
    df.loc[(new_unemp_loans) & (df['age'].between(41, 55)), 'income'] * np.random.randint(4, 6, size=df[(new_unemp_loans) & (df['age'].between(41, 55))].shape[0])

df.loc[(new_unemp_loans) & (df['age'].between(56, 59)), 'loan_amount'] = \
    df.loc[(new_unemp_loans) & (df['age'].between(56, 59)), 'income'] * np.random.randint(4, 6, size=df[(new_unemp_loans) & (df['age'].between(56, 59))].shape[0])

df.loc[(new_unemp_loans) & (df['age'] >= 60), 'loan_amount'] = \
    df.loc[(new_unemp_loans) & (df['age'] >= 60), 'income'] * np.random.randint(3, 5, size=df[(new_unemp_loans) & (df['age'] >= 60)].shape[0])

df.loc[new_unemp_loans, 'loan_amount'] = df.loc[new_unemp_loans, 'loan_amount'].astype(int)

print(f"Loans assigned to {new_unemp_loans.sum()} unemployed worst credit rows!")

Loans assigned to 255 unemployed worst credit rows!

In [68]:
df[new_unemp_loans]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5000,32,21932,363,3,0,0,87728,36
5001,70,11157,334,0,0,0,44628,36
5003,26,10918,342,3,0,0,43672,36
5004,52,29225,345,3,0,0,146125,36
5005,49,28952,308,3,0,0,115808,36
...,...,...,...,...,...,...,...,...
5258,30,14833,326,0,0,0,74165,36
5259,60,14347,314,0,0,0,43041,36
5260,28,15592,324,1,0,0,62368,36
5261,27,17727,368,3,0,0,70908,36
5262,36,26565,324,1,0,0,106260,36

In [70]:
import pandas as pd
import numpy as np
FILE = "csv-2/copy.csv"
df = pd.read_csv(FILE)

In [73]:
df.to_csv(FILE, index=False)

In [72]:
df.loc[
    (df["loan_amount"]==0)
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5000,32,0,363,3,0,0,0,36
5001,70,0,334,0,0,0,0,36
5002,53,0,400,3,0,0,0,36
5003,26,0,342,3,0,0,0,36
5004,52,0,345,3,0,0,0,36
...,...,...,...,...,...,...,...,...
5528,66,0,392,2,1,0,0,36
5529,44,0,400,2,1,0,0,36
5530,50,0,399,0,1,0,0,36
5531,33,0,341,0,1,0,0,36
5532,38,0,333,2,1,0,0,36