In [1]:
import pandas as pd

df = pd.read_csv('csv/loan_data.csv')

df.head(10)

   age  income  credit_score  existing_loans  employed  default
0   47  151735           616               1         1        0
1   40   72912           781               1         1        0
2   49  152455           568               2         0        0
3   60  120771           654               1         1        1
4   39   86572           767               1         1        0
5   39   49276           695               1         1        0
6   60  137459           790               1         1        0
7   51   55534           537               4         1        0
8   36   65670           674               1         1        0
9   48  112147           806               2         1        0

In [2]:
# Check missing values

print(df.isnull().sum())

# Data types
print(df.dtypes)

age               0
income            0
credit_score      0
existing_loans    0
employed          0
default           0
dtype: int64
age               int64
income            int64
credit_score      int64
existing_loans    int64
employed          int64
default           int64
dtype: object

In [3]:
percent_default = lambda a, b: (a/b)*100

(df["default"].value_counts()[0] / df["default"].count()) *100

np.float64(79.2)

In [4]:
total_defaults = df["default"].value_counts()[0]
total_counts = df["default"].count()
print(total_defaults, total_counts)

print(percent_default(total_defaults, total_counts))

# 79.2 % Loan default hai 
# 100 - 79.2 = 20.8 % logon ne loan repay kiya hai
total_non_defaults = df["default"].value_counts()[1]
print(percent_default(total_non_defaults, total_counts))

3960 5000
79.2
20.8

In [5]:
df["default"].count()

np.int64(5000)

In [6]:
df["default"].value_counts()

default
0    3960
1    1040
Name: count, dtype: int64

In [7]:
(54/100)*100

54.0

In [8]:
import pandas as pd

df = pd.read_csv('csv/loan_data.csv')
df.head()

   age  income  credit_score  existing_loans  employed  default
0   47  151735           616               1         1        0
1   40   72912           781               1         1        0
2   49  152455           568               2         0        0
3   60  120771           654               1         1        1
4   39   86572           767               1         1        0

In [9]:
# People who are not employed but have income
unemployed_with_income = df.loc[(df["employed"]== 0) & (df["income"] > 0)]
unemployed_with_income

      age  income  credit_score  existing_loans  employed  default
2      49  152455           568               2         0        0
30     34   89624           763               1         0        1
65     58  181932           626               3         0        0
67     54  117300           653               0         0        1
75     51  107442           662               0         0        1
...   ...     ...           ...             ...       ...      ...
4970   60  103865           696               1         0        0
4973   25   55191           688               0         0        0
4976   58  198795           695               2         0        1
4987   42   87710           694               4         0        1
4993   48  122358           723               3         0        1

[718 rows x 6 columns]

In [10]:
import numpy as np
len(unemployed_with_income)

718

In [11]:
df.loc[ (df["employed"]==0) & (df["income"]>0) & (df["age"]<60), "income" ] = 2000

In [12]:
df.loc[(df["employed"]==0) & (df["income"]>0) & (df["age"]<60)]

      age  income  credit_score  existing_loans  employed  default
2      49    2000           568               2         0        0
30     34    2000           763               1         0        1
65     58    2000           626               3         0        0
67     54    2000           653               0         0        1
75     51    2000           662               0         0        1
...   ...     ...           ...             ...       ...      ...
4961   29    2000           746               3         0        1
4973   25    2000           688               0         0        0
4976   58    2000           695               2         0        1
4987   42    2000           694               4         0        1
4993   48    2000           723               3         0        1

[663 rows x 6 columns]

In [13]:
df.isna().sum()

age               0
income            0
credit_score      0
existing_loans    0
employed          0
default           0
dtype: int64

In [14]:
import pandas as pd
df = pd.read_csv('csv/copy.csv')
df.head()

   age  income  credit_score  existing_loans  employed  default
0   47  151735           616               1         1        0
1   40   72912           781               1         1        0
2   49  152455           568               2         0        0
3   60  120771           654               1         1        1
4   39   86572           767               1         1        0

In [15]:
len_unemp_with_inc = len(df.loc[(df["employed"]==0) & (df["age"]<60) & (df["income"]>0)])
len_unemp_with_inc

663

In [16]:
import numpy as np

arr = np.random.randint(2000, 6000, size=(len_unemp_with_inc))
arr.size

663

In [17]:
df.loc[(df["employed"]==0) & (df["age"]<60) & (df["income"]>0), "income"] = arr

In [18]:
print("hello world")

hello world

In [19]:
df[df["income"]==2000]

Empty DataFrame
Columns: [age, income, credit_score, existing_loans, employed, default]
Index: []

In [20]:
df.head(100)

    age  income  credit_score  existing_loans  employed  default
0    47  151735           616               1         1        0
1    40   72912           781               1         1        0
2    49    3179           568               2         0        0
3    60  120771           654               1         1        1
4    39   86572           767               1         1        0
..  ...     ...           ...             ...       ...      ...
95   25    4873           770               1         0        1
96   45  139494           679               4         1        0
97   45  117067           794               1         1        0
98   42  121017           706               2         1        0
99   39   53932           842               5         1        0

[100 rows x 6 columns]

In [21]:
import numpy as np
len_retired_ppl = len(df.loc[(df["employed"]==0) & (df["age"]>=60) & (df["income"]>0)])

arr = np.random.randint(15000, 18000, size=len_retired_ppl)

arr.size

55

In [22]:
df.loc[(df["employed"]==0) & (df["age"]>=60) & (df["income"]>0), "income"] = arr

In [23]:
# df.loc[(df["employed"]==0) & (df["age"]<60) & (df["income"]>0)]

df.loc[(df["age"]>=60) & (df["employed"]==0)]

      age  income  credit_score  existing_loans  employed  default
106    64   15555           738               1         0        0
135    60   15100           708               0         0        0
209    70   16100           705               1         0        1
387    64   17347           536               3         0        1
393    63   15793           755               0         0        0
494    60   15137           680               0         0        0
624    61   15414           714               5         0        1
738    61   17747           652               2         0        0
880    70   17914           735               3         0        1
885    64   15483           729               3         0        0
967    63   16342           707               1         0        1
996    63   16665           654               2         0        0
1154   61   15474           812               3         0        0
1157   69   17334           676               3         0        1
1387   60   15576           666               1         0        0
1466   62   17959           623               3         0        0
1496   66   16009           669               0         0        1
1541   63   15347           797               3         0        0
1638   66   16709           725               1         0        1
1897   61   17876           746               2         0        0
1910   62   17048           705               4         0        1
2164   60   17898           824               1         0        0
2311   63   15030           628               2         0        1
2404   62   16720           664               0         0        0
2411   60   16822           784               3         0        1
2506   70   17605           651               3         0        0
2544   70   16898           635               3         0        0
2709   60   17136           621               0         0        0
2724   65   15183           677               1         0        1
2731   62   17537           655               3         0        1
2734   65   16423           743               2         0        0
2814   63   16624           683               1         0        0
2825   62   17720           646               3         0        0
2953   60   15540           575               3         0        0
3192   69   17704           614               1         0        0
3213   60   17089           732               0         0        0
3285   60   15323           495               2         0        1
3296   62   17874           741               3         0        1
3394   65   16413           715               5         0        1
3409   66   16666           798               1         0        1
3534   67   15210           618               3         0        0
3580   67   15599           719               3         0        0
3582   65   15477           658               4         0        0
3602   66   15374           830               3         0        1
3686   70   15721           667               4         0        0
3920   64   16572           621               5         0        1
3982   70   16860           800               3         0        0
3998   61   16981           706               1         0        1
4114   61   16725           630               3         0        0
4129   61   16920           798               0         0        0
4226   64   15375           712               1         0        1
4495   62   15233           628               3         0        1
4621   62   16726           706               1         0        0
4655   67   17096           816               2         0        0
4970   60   16664           696               1         0        0

In [24]:
import pandas as pd

df = pd.read_csv("csv/copy.csv")
df.head()

   age  income  credit_score  existing_loans  employed  default
0   47  151735           616               1         1        0
1   40   72912           781               1         1        0
2   49  152455           568               2         0        0
3   60  120771           654               1         1        1
4   39   86572           767               1         1        0

In [25]:
df.loc[df['existing_loans'] == 0, 'default'] = 0
df.iloc[35]

age                  27
income            35651
credit_score        772
existing_loans        0
employed              1
default               0
Name: 35, dtype: int64

In [26]:
df.loc[(df['existing_loans']<1)]

      age  income  credit_score  existing_loans  employed  default
35     27   35651           772               0         1        0
43     38  104353           900               0         1        0
46     36   80830           560               0         1        0
63     27   53782           775               0         1        0
67     54  117300           653               0         0        0
...   ...     ...           ...             ...       ...      ...
4957   54  141707           771               0         1        0
4959   48  104261           684               0         1        0
4966   30  119349           712               0         1        0
4973   25   55191           688               0         0        0
4998   51  135366           638               0         1        0

[653 rows x 6 columns]

In [27]:

emi = (33333 /90000)*100
print(f"{emi:.1f}")

37.0

In [28]:
df.loc[(df["income"]>50000)].shape[0]

4230

In [29]:
import numpy as np

loan_amount = 1200000  # base amount

# 10% randomness
randomness = np.random.uniform(0.9, 1.1, size=65)  # 90% to 110%
final_loan = np.array(loan_amount * randomness)

# Format each element
final_loan = np.round(final_loan)
final_loan.astype("int32")
print(final_loan)

[1315964. 1135481. 1196347. 1206976. 1184267. 1144538. 1268842. 1295802.
 1158641. 1232089. 1209203. 1241053. 1302296. 1221027. 1089430. 1194717.
 1276076. 1110450. 1286664. 1270720. 1290291. 1090254. 1148784. 1272534.
 1145673. 1271882. 1175441. 1256354. 1194373. 1202109. 1311917. 1191285.
 1133498. 1101115. 1211523. 1110382. 1307226. 1240819. 1305059. 1122361.
 1309167. 1209300. 1194873. 1169190. 1254834. 1096989. 1293569. 1119560.
 1292795. 1160423. 1090992. 1170179. 1303154. 1165194. 1108661. 1214895.
 1188246. 1308646. 1237596. 1178800. 1147801. 1160919. 1264598. 1301464.
 1212428.]

In [30]:
df["loan_amount"] = 0

In [31]:
df.head()

   age  income  credit_score  existing_loans  employed  default  loan_amount
0   47  151735           616               1         1        0            0
1   40   72912           781               1         1        0            0
2   49  152455           568               2         0        0            0
3   60  120771           654               1         1        1            0
4   39   86572           767               1         1        0            0

In [32]:
# Golden Customers

df.loc[
    (df["age"]>=35)&
    (df["income"]>=100000)&
    (df["credit_score"]>=800)&
    (df["existing_loans"]<=1)&
    (df["employed"]==1),
    "loan_amount"
] = final_loan

In [33]:
df.loc[
    (df["age"]>=35)&
    (df["income"]>=100000)&
    (df["credit_score"]>=800)&
    (df["existing_loans"]<=1)&
    (df["employed"]==1)
    ]

,age,income,credit_score,existing_loans,employed,default,loan_amount
43,38,104353,900,0,1,0,1315964
175,51,116425,823,1,1,0,1135481
225,55,112178,822,1,1,0,1196347
467,51,127224,806,1,1,0,1206976
490,41,107134,841,1,1,0,1184267
...,...,...,...,...,...,...,...
4708,53,150257,851,1,1,0,1147801
4733,47,111742,888,0,1,0,1160919
4836,36,109810,823,1,1,0,1264598
4849,47,100621,831,1,1,0,1301464
4884,49,119852,826,1,1,0,1212428

In [34]:
import numpy as np

loan_amount = 800000  # base amount

# 10% randomness
randomness = np.random.uniform(0.9, 1.1, size=975)  # 90% to 110%
final_loan = np.array(loan_amount * randomness)

# Format each element
final_loan = np.round(final_loan)
# final_loan.astype("int32")
# print(final_loan)

In [35]:
# Silver customers

medium_customers = ((df['income'].between(50000, 100000)) & 
              (df['credit_score'].between(550, 799)) & 
              (df['age'].between(30, 50)) & 
              (df['existing_loans'].between(1, 3))&
              (df['existing_loans']<=3))

df.loc[medium_customers]

,age,income,credit_score,existing_loans,employed,default,loan_amount
1,40,72912,781,1,1,0,0
4,39,86572,767,1,1,0,0
8,36,65670,674,1,1,0,0
10,36,66486,609,2,1,0,0
11,36,95557,782,1,1,0,0
...,...,...,...,...,...,...,...
4977,43,83800,665,1,1,0,0
4978,46,89107,720,1,1,0,0
4986,39,74420,697,1,1,0,0
4991,50,81283,651,1,1,0,0
4995,41,75968,745,2,1,0,0

In [36]:
df.loc[df["loan_amount"]>0]

,age,income,credit_score,existing_loans,employed,default,loan_amount
43,38,104353,900,0,1,0,1315964
175,51,116425,823,1,1,0,1135481
225,55,112178,822,1,1,0,1196347
467,51,127224,806,1,1,0,1206976
490,41,107134,841,1,1,0,1184267
...,...,...,...,...,...,...,...
4708,53,150257,851,1,1,0,1147801
4733,47,111742,888,0,1,0,1160919
4836,36,109810,823,1,1,0,1264598
4849,47,100621,831,1,1,0,1301464
4884,49,119852,826,1,1,0,1212428

In [37]:
df.head()

   age  income  credit_score  existing_loans  employed  default  loan_amount
0   47  151735           616               1         1        0            0
1   40   72912           781               1         1        0            0
2   49  152455           568               2         0        0            0
3   60  120771           654               1         1        1            0
4   39   86572           767               1         1        0            0

## Date :- 2026-04-18

In [38]:
FILE_PATH = "csv/copy.csv"

In [39]:
import pandas as pd
df = pd.read_csv(FILE_PATH)
df.head()

   age  income  credit_score  existing_loans  employed  default
0   47  151735           616               1         1        0
1   40   72912           781               1         1        0
2   49  152455           568               2         0        0
3   60  120771           654               1         1        1
4   39   86572           767               1         1        0

In [40]:
df.loc[
    (df["employed"]==0)&
    (df["credit_score"])
]

      age  income  credit_score  existing_loans  employed  default
30     34   89624           763               1         0        1
67     54  117300           653               0         0        1
103    32   68931           817               3         0        0
105    46   88032           471               1         0        1
115    45   69787           647               2         0        0
...   ...     ...           ...             ...       ...      ...
4912   51   86996           831               2         0        1
4915   44   87177           633               1         0        0
4941   39  111397           583               3         0        1
4976   58  198795           695               2         0        1
4993   48  122358           723               3         0        1

[360 rows x 6 columns]

### Date :-  2026-04-19

In [50]:
import pandas as pd
import numpy as np

In [63]:
tier1 = df.loc[
    (df["employed"]==0) &
    (df["credit_score"]<550) & 
    (df["age"]<30)
]
tier1

      age  income  credit_score  existing_loans  employed  default
991    25    4584           513               1         0        1
1573   25    4959           539               4         0        0
2154   26    3873           546               3         0        1
2970   25    3281           519               1         0        1
4163   25    3460           536               5         0        1
4747   28    3904           513               1         0        1

In [58]:
inc = np.random.randint(3000, 5000, size=tier1.shape[0])
inc

array([4584, 4959, 3873, 3281, 3460, 3904], dtype=int32)

In [61]:
df.loc[
    (df["employed"]==0) &
    (df["credit_score"]<550) & 
    (df["age"]<30), "income"
] = inc

In [67]:
tier1

      age  income  credit_score  existing_loans  employed  default
991    25    4584           513               1         0        1
1573   25    4959           539               4         0        0
2154   26    3873           546               3         0        1
2970   25    3281           519               1         0        1
4163   25    3460           536               5         0        1
4747   28    3904           513               1         0        1

In [83]:
tier11 = (df["employed"]==0) & \
(df["credit_score"]<550) & \
(df["age"]<30)

In [84]:
df[tier11]

      age  income  credit_score  existing_loans  employed  default
991    25    4584           513               0         0        0
1573   25    4959           539               1         0        0
2154   26    3873           546               0         0        0
2970   25    3281           519               1         0        1
4163   25    3460           536               0         0        0
4747   28    3904           513               0         0        0

In [79]:
# df.loc[tier11, 'existing_loans'] = np.random.randint(0, 2, size=tier11.sum())


df.loc[tier11]

      age  income  credit_score  existing_loans  employed  default
991    25    4584           513               0         0        0
1573   25    4959           539               1         0        0
2154   26    3873           546               0         0        0
2970   25    3281           519               1         0        1
4163   25    3460           536               0         0        0
4747   28    3904           513               0         0        0

In [78]:
# Agar existing_loans == 0, to default = 0 hona chahiye
df.loc[(df['existing_loans'] == 0) & (df['default'] == 1), 'default'] = 0

In [89]:
df[tier11].shape[0]

6

In [95]:
df.to_csv(FILE_PATH, index=False)

In [96]:
pd.read_csv(FILE_PATH)

      age  income  credit_score  existing_loans  employed  default
0      47  151735           616               1         1        0
1      40   72912           781               1         1        0
2      49  152455           568               2         0        0
3      60  120771           654               1         1        1
4      39   86572           767               1         1        0
...   ...     ...           ...             ...       ...      ...
4995   41   75968           745               2         1        0
4996   50  112508           768               3         1        0
4997   70  153435           788               2         1        0
4998   51  135366           638               0         1        0
4999   31   35738           674               1         1        0

[5000 rows x 6 columns]