In [1]:
import pandas as pd

df = pd.read_csv('csv/loan_data.csv')

df.head(10)

   age  income  credit_score  existing_loans  employed  default
0   47  151735           616               1         1        0
1   40   72912           781               1         1        0
2   49  152455           568               2         0        0
3   60  120771           654               1         1        1
4   39   86572           767               1         1        0
5   39   49276           695               1         1        0
6   60  137459           790               1         1        0
7   51   55534           537               4         1        0
8   36   65670           674               1         1        0
9   48  112147           806               2         1        0

In [2]:
# Check missing values

print(df.isnull().sum())

# Data types
print(df.dtypes)

age               0
income            0
credit_score      0
existing_loans    0
employed          0
default           0
dtype: int64
age               int64
income            int64
credit_score      int64
existing_loans    int64
employed          int64
default           int64
dtype: object

In [3]:
percent_default = lambda a, b: (a/b)*100

(df["default"].value_counts()[0] / df["default"].count()) *100

np.float64(79.2)

In [4]:
total_defaults = df["default"].value_counts()[0]
total_counts = df["default"].count()
print(total_defaults, total_counts)

print(percent_default(total_defaults, total_counts))

# 79.2 % Loan default hai 
# 100 - 79.2 = 20.8 % logon ne loan repay kiya hai
total_non_defaults = df["default"].value_counts()[1]
print(percent_default(total_non_defaults, total_counts))

3960 5000
79.2
20.8

In [5]:
df["default"].count()

np.int64(5000)

In [6]:
df["default"].value_counts()

default
0    3960
1    1040
Name: count, dtype: int64

In [7]:
(54/100)*100

54.0

In [8]:
import pandas as pd

df = pd.read_csv('csv/loan_data.csv')
df.head()

   age  income  credit_score  existing_loans  employed  default
0   47  151735           616               1         1        0
1   40   72912           781               1         1        0
2   49  152455           568               2         0        0
3   60  120771           654               1         1        1
4   39   86572           767               1         1        0

In [9]:
# People who are not employed but have income
unemployed_with_income = df.loc[(df["employed"]== 0) & (df["income"] > 0)]
unemployed_with_income

      age  income  credit_score  existing_loans  employed  default
2      49  152455           568               2         0        0
30     34   89624           763               1         0        1
65     58  181932           626               3         0        0
67     54  117300           653               0         0        1
75     51  107442           662               0         0        1
...   ...     ...           ...             ...       ...      ...
4970   60  103865           696               1         0        0
4973   25   55191           688               0         0        0
4976   58  198795           695               2         0        1
4987   42   87710           694               4         0        1
4993   48  122358           723               3         0        1

[718 rows x 6 columns]

In [10]:
import numpy as np
len(unemployed_with_income)

718

In [11]:
df.loc[ (df["employed"]==0) & (df["income"]>0) & (df["age"]<60), "income" ] = 2000

In [12]:
df.loc[(df["employed"]==0) & (df["income"]>0) & (df["age"]<60)]

      age  income  credit_score  existing_loans  employed  default
2      49    2000           568               2         0        0
30     34    2000           763               1         0        1
65     58    2000           626               3         0        0
67     54    2000           653               0         0        1
75     51    2000           662               0         0        1
...   ...     ...           ...             ...       ...      ...
4961   29    2000           746               3         0        1
4973   25    2000           688               0         0        0
4976   58    2000           695               2         0        1
4987   42    2000           694               4         0        1
4993   48    2000           723               3         0        1

[663 rows x 6 columns]

In [13]:
df.isna().sum()

age               0
income            0
credit_score      0
existing_loans    0
employed          0
default           0
dtype: int64

In [14]:
import pandas as pd
df = pd.read_csv('csv/copy.csv')
df.head()

   age  income  credit_score  existing_loans  employed  default
0   47  151735           616               1         1        0
1   40   72912           781               1         1        0
2   49  152455           568               2         0        0
3   60  120771           654               1         1        1
4   39   86572           767               1         1        0

In [15]:
len_unemp_with_inc = len(df.loc[(df["employed"]==0) & (df["age"]<60) & (df["income"]>0)])
len_unemp_with_inc

663

In [16]:
import numpy as np

arr = np.random.randint(2000, 6000, size=(len_unemp_with_inc))
arr.size

663

In [17]:
df.loc[(df["employed"]==0) & (df["age"]<60) & (df["income"]>0), "income"] = arr

In [18]:
print("hello world")

hello world

In [19]:
df[df["income"]==2000]

Empty DataFrame
Columns: [age, income, credit_score, existing_loans, employed, default]
Index: []

In [20]:
df.head(100)

    age  income  credit_score  existing_loans  employed  default
0    47  151735           616               1         1        0
1    40   72912           781               1         1        0
2    49    4160           568               2         0        0
3    60  120771           654               1         1        1
4    39   86572           767               1         1        0
..  ...     ...           ...             ...       ...      ...
95   25    3929           770               1         0        1
96   45  139494           679               4         1        0
97   45  117067           794               1         1        0
98   42  121017           706               2         1        0
99   39   53932           842               5         1        0

[100 rows x 6 columns]

In [21]:
import numpy as np
len_retired_ppl = len(df.loc[(df["employed"]==0) & (df["age"]>=60) & (df["income"]>0)])

arr = np.random.randint(15000, 18000, size=len_retired_ppl)

arr.size

55

In [22]:
df.loc[(df["employed"]==0) & (df["age"]>=60) & (df["income"]>0), "income"] = arr

In [23]:
# df.loc[(df["employed"]==0) & (df["age"]<60) & (df["income"]>0)]

df.loc[(df["age"]>=60) & (df["employed"]==0)]

      age  income  credit_score  existing_loans  employed  default
106    64   17571           738               1         0        0
135    60   16530           708               0         0        0
209    70   17460           705               1         0        1
387    64   15870           536               3         0        1
393    63   15121           755               0         0        0
494    60   15240           680               0         0        0
624    61   17313           714               5         0        1
738    61   16394           652               2         0        0
880    70   16660           735               3         0        1
885    64   15438           729               3         0        0
967    63   17536           707               1         0        1
996    63   17489           654               2         0        0
1154   61   17351           812               3         0        0
1157   69   17279           676               3         0        1
1387   60   15709           666               1         0        0
1466   62   17304           623               3         0        0
1496   66   16813           669               0         0        1
1541   63   15265           797               3         0        0
1638   66   15167           725               1         0        1
1897   61   15526           746               2         0        0
1910   62   16400           705               4         0        1
2164   60   15003           824               1         0        0
2311   63   15675           628               2         0        1
2404   62   16742           664               0         0        0
2411   60   16101           784               3         0        1
2506   70   16778           651               3         0        0
2544   70   16657           635               3         0        0
2709   60   17136           621               0         0        0
2724   65   16001           677               1         0        1
2731   62   16430           655               3         0        1
2734   65   17199           743               2         0        0
2814   63   16119           683               1         0        0
2825   62   16376           646               3         0        0
2953   60   17634           575               3         0        0
3192   69   16478           614               1         0        0
3213   60   16530           732               0         0        0
3285   60   15193           495               2         0        1
3296   62   15057           741               3         0        1
3394   65   16860           715               5         0        1
3409   66   16543           798               1         0        1
3534   67   17329           618               3         0        0
3580   67   17275           719               3         0        0
3582   65   15574           658               4         0        0
3602   66   15093           830               3         0        1
3686   70   15686           667               4         0        0
3920   64   16124           621               5         0        1
3982   70   17631           800               3         0        0
3998   61   17955           706               1         0        1
4114   61   16714           630               3         0        0
4129   61   17052           798               0         0        0
4226   64   16238           712               1         0        1
4495   62   17573           628               3         0        1
4621   62   16566           706               1         0        0
4655   67   15026           816               2         0        0
4970   60   15296           696               1         0        0

In [24]:
import pandas as pd

df = pd.read_csv("csv/copy.csv")
df.head()

   age  income  credit_score  existing_loans  employed  default
0   47  151735           616               1         1        0
1   40   72912           781               1         1        0
2   49  152455           568               2         0        0
3   60  120771           654               1         1        1
4   39   86572           767               1         1        0

In [25]:
df.loc[df['existing_loans'] == 0, 'default'] = 0
df.iloc[35]

age                  27
income            35651
credit_score        772
existing_loans        0
employed              1
default               0
Name: 35, dtype: int64

In [26]:
df.loc[(df['existing_loans']<1)]

      age  income  credit_score  existing_loans  employed  default
35     27   35651           772               0         1        0
43     38  104353           900               0         1        0
46     36   80830           560               0         1        0
63     27   53782           775               0         1        0
67     54  117300           653               0         0        0
...   ...     ...           ...             ...       ...      ...
4957   54  141707           771               0         1        0
4959   48  104261           684               0         1        0
4966   30  119349           712               0         1        0
4973   25   55191           688               0         0        0
4998   51  135366           638               0         1        0

[653 rows x 6 columns]

In [27]:

emi = (33333 /90000)*100
print(f"{emi:.1f}")

37.0

In [28]:
df.loc[(df["income"]>50000)].shape[0]

4230

In [37]:
import numpy as np

loan_amount = 1200000  # base amount

# 10% randomness
randomness = np.random.uniform(0.9, 1.1, size=65)  # 90% to 110%
final_loan = np.array(loan_amount * randomness)

# Format each element
final_loan = np.round(final_loan)
final_loan.astype("int32")
print(final_loan)

[1194836. 1260651. 1301295. 1171838. 1266349. 1133703. 1137521. 1132502.
 1290401. 1144343. 1276470. 1318433. 1089392. 1103231. 1188463. 1145236.
 1080710. 1318305. 1133015. 1091487. 1312794. 1301835. 1114298. 1155853.
 1205157. 1119853. 1197321. 1222765. 1316219. 1174905. 1204724. 1118647.
 1227201. 1238574. 1172900. 1295884. 1258903. 1092891. 1156359. 1311315.
 1150905. 1220523. 1096822. 1092615. 1127757. 1280507. 1127371. 1252284.
 1239597. 1217711. 1306319. 1318085. 1295997. 1134977. 1149394. 1237793.
 1127562. 1289304. 1141310. 1207161. 1315070. 1214646. 1135504. 1135517.
 1202125.]

In [32]:
df["loan_amount"] = 0

In [35]:
df.head()

   age  income  credit_score  existing_loans  employed  default  loan_amount
0   47  151735           616               1         1        0            0
1   40   72912           781               1         1        0            0
2   49  152455           568               2         0        0            0
3   60  120771           654               1         1        1            0
4   39   86572           767               1         1        0            0

In [38]:
# Golden Customers

df.loc[
    (df["age"]>=35)&
    (df["income"]>=100000)&
    (df["credit_score"]>=800)&
    (df["existing_loans"]<=1)&
    (df["employed"]==1),
    "loan_amount"
] = final_loan

In [39]:
df.loc[
    (df["age"]>=35)&
    (df["income"]>=100000)&
    (df["credit_score"]>=800)&
    (df["existing_loans"]<=1)&
    (df["employed"]==1)
    ]

,age,income,credit_score,existing_loans,employed,default,loan_amount
43,38,104353,900,0,1,0,1194836
175,51,116425,823,1,1,0,1260651
225,55,112178,822,1,1,0,1301295
467,51,127224,806,1,1,0,1171838
490,41,107134,841,1,1,0,1266349
...,...,...,...,...,...,...,...
4708,53,150257,851,1,1,0,1315070
4733,47,111742,888,0,1,0,1214646
4836,36,109810,823,1,1,0,1135504
4849,47,100621,831,1,1,0,1135517
4884,49,119852,826,1,1,0,1202125

In [49]:
import numpy as np

loan_amount = 800000  # base amount

# 10% randomness
randomness = np.random.uniform(0.9, 1.1, size=975)  # 90% to 110%
final_loan = np.array(loan_amount * randomness)

# Format each element
final_loan = np.round(final_loan)
# final_loan.astype("int32")
# print(final_loan)

In [54]:
# Silver customers

medium_customers = ((df['income'].between(50000, 100000)) & 
              (df['credit_score'].between(550, 799)) & 
              (df['age'].between(30, 50)) & 
              (df['existing_loans'].between(1, 3))&
              (df['existing_loans']<=3))

df.loc[medium_customers]

,age,income,credit_score,existing_loans,employed,default,loan_amount
1,40,72912,781,1,1,0,837542
4,39,86572,767,1,1,0,847926
8,36,65670,674,1,1,0,722142
10,36,66486,609,2,1,0,822622
11,36,95557,782,1,1,0,864617
...,...,...,...,...,...,...,...
4977,43,83800,665,1,1,0,856175
4978,46,89107,720,1,1,0,860716
4986,39,74420,697,1,1,0,808865
4991,50,81283,651,1,1,0,726369
4995,41,75968,745,2,1,0,839544

In [57]:
df.loc[df["loan_amount"]>0]

,age,income,credit_score,existing_loans,employed,default,loan_amount
1,40,72912,781,1,1,0,837542
4,39,86572,767,1,1,0,847926
8,36,65670,674,1,1,0,722142
10,36,66486,609,2,1,0,822622
11,36,95557,782,1,1,0,864617
...,...,...,...,...,...,...,...
4977,43,83800,665,1,1,0,856175
4978,46,89107,720,1,1,0,860716
4986,39,74420,697,1,1,0,808865
4991,50,81283,651,1,1,0,726369
4995,41,75968,745,2,1,0,839544

In [58]:
df.head()

   age  income  credit_score  existing_loans  employed  default  loan_amount
0   47  151735           616               1         1        0            0
1   40   72912           781               1         1        0       837542
2   49  152455           568               2         0        0            0
3   60  120771           654               1         1        1            0
4   39   86572           767               1         1        0       847926