In [1]:
print("Hello World")

Hello World

In [2]:
import pandas as pd
import numpy as np
FILE = "csv-2/copy.csv"
df = pd.read_csv(FILE)

In [2]:
df.head()

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,526920,36
1,40,69517,781,1,1,0,417102,36
2,49,28572,568,2,0,0,83408,36
3,60,71067,654,1,1,1,284268,36
4,39,68930,767,1,1,0,413580,36

## Assigning Loans to EMPLOYED people

In [3]:
## Worst Cibil 

worst_emp = (df['employed'] == 1) & (df['credit_score'] < 400)

In [4]:
worst_emp = (df['employed'] == 1) & (df['credit_score'] < 400)


df.loc[(worst_emp) & (df['age'].between(30, 40)), 'loan_amount'] = \
    df.loc[(worst_emp) & (df['age'].between(30, 40)), 'income'] * np.random.randint(4, 6, size=df[(worst_emp) & (df['age'].between(30, 40))].shape[0])

df.loc[(worst_emp) & (df['age'].between(41, 55)), 'loan_amount'] = \
    np.maximum(df.loc[(worst_emp) & (df['age'].between(41, 55)), 'income'] * np.random.randint(4, 6, size=df[(worst_emp) & (df['age'].between(41, 55))].shape[0]), 500000)



df.loc[worst_emp, 'loan_amount'] = df.loc[worst_emp, 'loan_amount'].astype(int)

print(f"Employed worst credit loans assigned! {worst_emp.sum()} rows now")

Employed worst credit loans assigned! 269 rows now

In [5]:
df[worst_emp]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
1507,53,109011,399,3,1,1,545055,36
1561,33,53733,375,1,1,0,214932,36
5263,70,0,361,2,1,0,0,36
5264,68,0,341,0,1,0,0,36
5265,43,0,332,2,1,0,500000,36
...,...,...,...,...,...,...,...,...
5527,58,0,314,0,1,0,0,36
5528,66,0,392,2,1,0,0,36
5530,50,0,399,0,1,0,500000,36
5531,33,0,341,0,1,0,0,36
5532,38,0,333,2,1,0,0,36

In [6]:
## POOR cibil 
poor_emp = (df['employed'] == 1) & (df['credit_score'].between(401, 550))

In [7]:

df.loc[(poor_emp) & (df['age'].between(25, 29)), 'loan_amount'] = \
    df.loc[(poor_emp) & (df['age'].between(25, 29)), 'income'] * np.random.randint(5, 7, size=df[(poor_emp) & (df['age'].between(25, 29))].shape[0])

df.loc[(poor_emp) & (df['age'].between(30, 40)), 'loan_amount'] = \
    df.loc[(poor_emp) & (df['age'].between(30, 40)), 'income'] * np.random.randint(5, 7, size=df[(poor_emp) & (df['age'].between(30, 40))].shape[0])

df.loc[(poor_emp) & (df['age'].between(41, 55)), 'loan_amount'] = \
    df.loc[(poor_emp) & (df['age'].between(41, 55)), 'income'] * np.random.randint(5, 7, size=df[(poor_emp) & (df['age'].between(41, 55))].shape[0])

df.loc[(poor_emp) & (df['age'].between(56, 59)), 'loan_amount'] = \
    df.loc[(poor_emp) & (df['age'].between(56, 59)), 'income'] * np.random.randint(5, 7, size=df[(poor_emp) & (df['age'].between(56, 59))].shape[0])

df.loc[(poor_emp) & (df['age'] >= 60), 'loan_amount'] = \
    df.loc[(poor_emp) & (df['age'] >= 60), 'income'] * np.random.randint(3, 5, size=df[(poor_emp) & (df['age'] >= 60)].shape[0])

df.loc[poor_emp, 'loan_amount'] = df.loc[poor_emp, 'loan_amount'].astype(int)

print(f"Employed poor credit loans assigned! {poor_emp.sum()} rows")

Employed poor credit loans assigned! 141 rows

In [8]:
df[poor_emp]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
7,51,117736,537,4,1,0,588680,36
54,54,151874,510,5,1,1,759370,36
89,48,118310,543,0,1,0,591550,36
202,54,104257,484,2,1,0,625542,36
226,42,67869,500,1,1,0,407214,36
...,...,...,...,...,...,...,...,...
4722,42,65760,509,0,1,0,394560,36
4774,25,30600,517,3,1,0,153000,36
4948,37,79987,486,3,1,0,399935,36
4953,53,152259,544,1,1,0,761295,36
4960,38,65380,516,1,1,0,326900,36

In [9]:
## GOOD cibil 
good_emp = (df['employed'] == 1) & (df['credit_score'].between(551, 699))

In [10]:

df.loc[(good_emp) & (df['age'].between(25, 29)), 'loan_amount'] = \
    df.loc[(good_emp) & (df['age'].between(25, 29)), 'income'] * np.random.randint(5, 8, size=df[(good_emp) & (df['age'].between(25, 29))].shape[0])

df.loc[(good_emp) & (df['age'].between(30, 40)), 'loan_amount'] = \
    df.loc[(good_emp) & (df['age'].between(30, 40)), 'income'] * np.random.randint(5, 8, size=df[(good_emp) & (df['age'].between(30, 40))].shape[0])

df.loc[(good_emp) & (df['age'].between(41, 55)), 'loan_amount'] = \
    df.loc[(good_emp) & (df['age'].between(41, 55)), 'income'] * np.random.randint(5, 8, size=df[(good_emp) & (df['age'].between(41, 55))].shape[0])

df.loc[(good_emp) & (df['age'].between(56, 59)), 'loan_amount'] = \
    df.loc[(good_emp) & (df['age'].between(56, 59)), 'income'] * np.random.randint(5, 8, size=df[(good_emp) & (df['age'].between(56, 59))].shape[0])

df.loc[(good_emp) & (df['age'] >= 60), 'loan_amount'] = \
    df.loc[(good_emp) & (df['age'] >= 60), 'income'] * np.random.randint(4, 6, size=df[(good_emp) & (df['age'] >= 60)].shape[0])

df.loc[good_emp, 'loan_amount'] = df.loc[good_emp, 'loan_amount'].astype(int)

print(f"Employed good credit loans assigned! {good_emp.sum()} rows")

Employed good credit loans assigned! 2023 rows

In [11]:
df[good_emp]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,632304,36
3,60,71067,654,1,1,1,284268,36
5,39,67947,695,1,1,0,475629,36
8,36,68281,674,1,1,0,341405,36
10,36,76048,609,2,1,0,380240,36
...,...,...,...,...,...,...,...,...
4990,25,30843,667,2,1,0,154215,36
4991,50,152453,651,1,1,0,762265,36
4992,40,84042,693,1,1,1,588294,36
4998,51,166975,638,0,1,0,1001850,36
4999,31,48188,674,1,1,0,337316,36

In [12]:
## BEST cibil 
best_emp = (df['employed'] == 1) & (df['credit_score'] >= 700)

In [13]:

df.loc[(best_emp) & (df['age'].between(25, 29)), 'loan_amount'] = \
    df.loc[(best_emp) & (df['age'].between(25, 29)), 'income'] * np.random.randint(6, 9, size=df[(best_emp) & (df['age'].between(25, 29))].shape[0])

df.loc[(best_emp) & (df['age'].between(30, 40)), 'loan_amount'] = \
    df.loc[(best_emp) & (df['age'].between(30, 40)), 'income'] * np.random.randint(6, 9, size=df[(best_emp) & (df['age'].between(30, 40))].shape[0])

df.loc[(best_emp) & (df['age'].between(41, 55)), 'loan_amount'] = \
    df.loc[(best_emp) & (df['age'].between(41, 55)), 'income'] * np.random.randint(6, 9, size=df[(best_emp) & (df['age'].between(41, 55))].shape[0])

df.loc[(best_emp) & (df['age'].between(56, 59)), 'loan_amount'] = \
    df.loc[(best_emp) & (df['age'].between(56, 59)), 'income'] * np.random.randint(6, 9, size=df[(best_emp) & (df['age'].between(56, 59))].shape[0])

df.loc[(best_emp) & (df['age'] >= 60), 'loan_amount'] = \
    df.loc[(best_emp) & (df['age'] >= 60), 'income'] * np.random.randint(5, 7, size=df[(best_emp) & (df['age'] >= 60)].shape[0])

df.loc[best_emp, 'loan_amount'] = df.loc[best_emp, 'loan_amount'].astype(int)

print(f"Employed best credit loans assigned! {best_emp.sum()} rows")

Employed best credit loans assigned! 2116 rows

In [14]:
df[best_emp]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
1,40,69517,781,1,1,0,417102,36
4,39,68930,767,1,1,0,482510,36
6,60,73017,790,1,1,0,438102,36
9,48,149422,806,2,1,0,1045954,36
11,36,66951,782,1,1,0,468657,36
...,...,...,...,...,...,...,...,...
4985,61,73889,735,2,1,0,443334,36
4994,34,50808,839,1,1,0,304848,36
4995,41,69736,745,2,1,0,488152,36
4996,50,103089,768,3,1,0,721623,36
4997,70,89423,788,2,1,0,447115,36

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,526920,36
1,40,69517,781,1,1,0,417102,36
2,49,28572,568,2,0,0,83408,36
3,60,71067,654,1,1,1,284268,36
4,39,68930,767,1,1,0,413580,36
...,...,...,...,...,...,...,...,...
4995,41,69736,745,2,1,0,557888,36
4996,50,103089,768,3,1,0,721623,36
4997,70,89423,788,2,1,0,536538,36
4998,51,166975,638,0,1,0,834875,36
4999,31,48188,674,1,1,0,289128,36

In [15]:
# Safe point

df.to_csv(FILE, index=False)

In [50]:
import pandas as pd
df = pd.read_csv(FILE)
df.head()

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,526920,36
1,40,69517,781,1,1,0,417102,36
2,49,28572,568,2,0,0,83408,36
3,60,71067,654,1,1,1,284268,36
4,39,68930,767,1,1,0,413580,36

In [16]:
df.loc[
    (df["loan_amount"]>0)
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,632304,36
1,40,69517,781,1,1,0,417102,36
2,49,28572,568,2,0,0,83408,36
3,60,71067,654,1,1,1,284268,36
4,39,68930,767,1,1,0,482510,36
...,...,...,...,...,...,...,...,...
5516,41,0,390,3,1,0,500000,36
5519,44,0,305,1,1,0,500000,36
5521,42,0,387,2,1,0,500000,36
5524,44,0,359,3,1,0,500000,36
5530,50,0,399,0,1,0,500000,36

### Adding new rows for unemployed persons with worst credit score

In [17]:
import numpy as np

# Create 213 rows
new_rows_unemp = 263

new_data_unemp = {
    'age': np.random.randint(25, 71, size=new_rows_unemp),
    'income': 0,
    'credit_score': np.random.randint(300, 401, size=new_rows_unemp),
    'existing_loans': np.random.randint(0, 4, size=new_rows_unemp),
    'employed': 0,
    'default': 0,
    'loan_amount': 0,
    'loan_tenure_months': 36
}

new_df_unemp = pd.DataFrame(new_data_unemp)

# Append to main df
df = pd.concat([df, new_df_unemp], ignore_index=True)

print(f"Added {new_rows_unemp} unemployed worst credit rows!")
print(f"Total rows now: {df.shape[0]}")

Added 263 unemployed worst credit rows!
Total rows now: 5796

In [18]:
df.loc[
    (df["loan_amount"]==0)
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5000,32,0,363,3,0,0,0,36
5001,70,0,334,0,0,0,0,36
5002,53,0,400,3,0,0,0,36
5003,26,0,342,3,0,0,0,36
5004,52,0,345,3,0,0,0,36
...,...,...,...,...,...,...,...,...
5791,36,0,353,1,0,0,0,36
5792,47,0,304,0,0,0,0,36
5793,68,0,351,1,0,0,0,36
5794,68,0,368,2,0,0,0,36
5795,60,0,397,2,0,0,0,36

In [54]:
# Create 190 rows
new_rows_emp = 270

new_data_emp = {
    'age': np.random.randint(25, 71, size=new_rows_emp),
    'income': 0,
    'credit_score': np.random.randint(300, 401, size=new_rows_emp),
    'existing_loans': np.random.randint(0, 4, size=new_rows_emp),
    'employed': 1,
    'default': 0,
    'loan_amount': 0,
    'loan_tenure_months': 36
}

new_df_emp = pd.DataFrame(new_data_emp)

# Append to main df
df = pd.concat([df, new_df_emp], ignore_index=True)

print(f"Added {new_rows_emp} employed worst credit rows!")
print(f"Total rows now: {df.shape[0]}")

Added 270 employed worst credit rows!
Total rows now: 5533

In [19]:
df.shape

(5796, 8)

In [20]:
df.loc[
    (df["employed"]==1) &
    (df["loan_amount"]==0)
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5263,70,0,361,2,1,0,0,36
5264,68,0,341,0,1,0,0,36
5266,37,0,325,0,1,0,0,36
5269,60,0,340,1,1,0,0,36
5271,34,0,356,3,1,0,0,36
...,...,...,...,...,...,...,...,...
5527,58,0,314,0,1,0,0,36
5528,66,0,392,2,1,0,0,36
5529,44,0,400,2,1,0,0,36
5531,33,0,341,0,1,0,0,36
5532,38,0,333,2,1,0,0,36

In [21]:
df.loc[
    (df["employed"]==0) &
    (df["loan_amount"]==0)
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5000,32,0,363,3,0,0,0,36
5001,70,0,334,0,0,0,0,36
5002,53,0,400,3,0,0,0,36
5003,26,0,342,3,0,0,0,36
5004,52,0,345,3,0,0,0,36
...,...,...,...,...,...,...,...,...
5791,36,0,353,1,0,0,0,36
5792,47,0,304,0,0,0,0,36
5793,68,0,351,1,0,0,0,36
5794,68,0,368,2,0,0,0,36
5795,60,0,397,2,0,0,0,36

In [58]:
# Safe point 

df.to_csv(FILE, index=False)

In [22]:
new_unemp = (df['employed'] == 0) & (df['income'] == 0)

In [23]:
df[new_unemp]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5000,32,0,363,3,0,0,0,36
5001,70,0,334,0,0,0,0,36
5002,53,0,400,3,0,0,0,36
5003,26,0,342,3,0,0,0,36
5004,52,0,345,3,0,0,0,36
...,...,...,...,...,...,...,...,...
5791,36,0,353,1,0,0,0,36
5792,47,0,304,0,0,0,0,36
5793,68,0,351,1,0,0,0,36
5794,68,0,368,2,0,0,0,36
5795,60,0,397,2,0,0,0,36

In [24]:

df.loc[(new_unemp) & (df['age'].between(25, 30)), 'income'] = \
    np.random.randint(10000, 18000, size=df[(new_unemp) & (df['age'].between(25, 30))].shape[0])

df.loc[(new_unemp) & (df['age'].between(31, 35)), 'income'] = \
    np.random.randint(15000, 25000, size=df[(new_unemp) & (df['age'].between(31, 35))].shape[0])

df.loc[(new_unemp) & (df['age'].between(36, 45)), 'income'] = \
    np.random.randint(26000, 28000, size=df[(new_unemp) & (df['age'].between(36, 45))].shape[0])

df.loc[(new_unemp) & (df['age'].between(46, 55)), 'income'] = \
    np.random.randint(28000, 30000, size=df[(new_unemp) & (df['age'].between(46, 55))].shape[0])

df.loc[(new_unemp) & (df['age'].between(56, 59)), 'income'] = \
    np.random.randint(20000, 22000, size=df[(new_unemp) & (df['age'].between(56, 59))].shape[0])

df.loc[(new_unemp) & (df['age'] >= 60), 'income'] = \
    np.random.randint(8000, 15000, size=df[(new_unemp) & (df['age'] >= 60)].shape[0])

print(f"Income assigned to {new_unemp.sum()} unemployed rows!")

Income assigned to 526 unemployed rows!

In [25]:
df[new_unemp]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5000,32,19523,363,3,0,0,0,36
5001,70,13433,334,0,0,0,0,36
5002,53,29201,400,3,0,0,0,36
5003,26,17421,342,3,0,0,0,36
5004,52,29260,345,3,0,0,0,36
...,...,...,...,...,...,...,...,...
5791,36,27884,353,1,0,0,0,36
5792,47,28029,304,0,0,0,0,36
5793,68,11748,351,1,0,0,0,36
5794,68,10998,368,2,0,0,0,36
5795,60,13191,397,2,0,0,0,36

In [26]:

df.loc[(new_emp) & (df['age'].between(25, 28)), 'income'] = \
    np.random.randint(20000, 35000, size=df[(new_emp) & (df['age'].between(25, 28))].shape[0])

df.loc[(new_emp) & (df['age'].between(29, 30)), 'income'] = \
    np.random.randint(33000, 40000, size=df[(new_emp) & (df['age'].between(29, 30))].shape[0])

df.loc[(new_emp) & (df['age'].between(31, 35)), 'income'] = \
    np.random.randint(45000, 63000, size=df[(new_emp) & (df['age'].between(31, 35))].shape[0])

df.loc[(new_emp) & (df['age'].between(36, 45)), 'income'] = \
    np.random.randint(65000, 85000, size=df[(new_emp) & (df['age'].between(36, 45))].shape[0])

df.loc[(new_emp) & (df['age'].between(46, 55)), 'income'] = \
    np.random.randint(100000, 180000, size=df[(new_emp) & (df['age'].between(46, 55))].shape[0])

df.loc[(new_emp) & (df['age'].between(56, 59)), 'income'] = \
    np.random.randint(100000, 140000, size=df[(new_emp) & (df['age'].between(56, 59))].shape[0])

df.loc[(new_emp) & (df['age'] >= 60), 'income'] = \
    np.random.randint(70000, 100000, size=df[(new_emp) & (df['age'] >= 60)].shape[0])

print(f"Income assigned to {new_emp.sum()} employed rows!")

NameError: name 'new_emp' is not defined

In [66]:
df[new_emp]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5263,70,85959,361,2,1,0,0,36
5264,68,93605,341,0,1,0,0,36
5265,43,74005,332,2,1,0,0,36
5266,37,82908,325,0,1,0,0,36
5267,45,80298,330,2,1,0,0,36
...,...,...,...,...,...,...,...,...
5528,66,96365,392,2,1,0,0,36
5529,44,80276,400,2,1,0,0,36
5530,50,173586,399,0,1,0,0,36
5531,33,56839,341,0,1,0,0,36
5532,38,70482,333,2,1,0,0,36

In [27]:
# Unemployed worst cibil 

new_unemp_loans = (df['employed'] == 0) & (df['loan_amount'] == 0) & (df['credit_score'] < 400)

df.loc[(new_unemp_loans) & (df['age'].between(25, 29)), 'loan_amount'] = \
    df.loc[(new_unemp_loans) & (df['age'].between(25, 29)), 'income'] * np.random.randint(4, 6, size=df[(new_unemp_loans) & (df['age'].between(25, 29))].shape[0])

df.loc[(new_unemp_loans) & (df['age'].between(30, 40)), 'loan_amount'] = \
    df.loc[(new_unemp_loans) & (df['age'].between(30, 40)), 'income'] * np.random.randint(4, 6, size=df[(new_unemp_loans) & (df['age'].between(30, 40))].shape[0])

df.loc[(new_unemp_loans) & (df['age'].between(41, 55)), 'loan_amount'] = \
    df.loc[(new_unemp_loans) & (df['age'].between(41, 55)), 'income'] * np.random.randint(4, 6, size=df[(new_unemp_loans) & (df['age'].between(41, 55))].shape[0])

df.loc[(new_unemp_loans) & (df['age'].between(56, 59)), 'loan_amount'] = \
    df.loc[(new_unemp_loans) & (df['age'].between(56, 59)), 'income'] * np.random.randint(4, 6, size=df[(new_unemp_loans) & (df['age'].between(56, 59))].shape[0])

df.loc[(new_unemp_loans) & (df['age'] >= 60), 'loan_amount'] = \
    df.loc[(new_unemp_loans) & (df['age'] >= 60), 'income'] * np.random.randint(3, 5, size=df[(new_unemp_loans) & (df['age'] >= 60)].shape[0])

df.loc[new_unemp_loans, 'loan_amount'] = df.loc[new_unemp_loans, 'loan_amount'].astype(int)

print(f"Loans assigned to {new_unemp_loans.sum()} unemployed worst credit rows!")

Loans assigned to 516 unemployed worst credit rows!

In [28]:
df[new_unemp_loans]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5000,32,19523,363,3,0,0,97615,36
5001,70,13433,334,0,0,0,53732,36
5003,26,17421,342,3,0,0,69684,36
5004,52,29260,345,3,0,0,117040,36
5005,49,29392,308,3,0,0,117568,36
...,...,...,...,...,...,...,...,...
5791,36,27884,353,1,0,0,139420,36
5792,47,28029,304,0,0,0,112116,36
5793,68,11748,351,1,0,0,35244,36
5794,68,10998,368,2,0,0,32994,36
5795,60,13191,397,2,0,0,52764,36

In [4]:
import pandas as pd
import numpy as np
FILE = "csv-2/copy.csv"
df = pd.read_csv(FILE)

In [73]:
df.to_csv(FILE, index=False)

In [29]:
df.loc[
    (df["loan_amount"]==0)
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5002,53,29201,400,3,0,0,0,36
5024,38,27369,400,2,0,0,0,36
5044,33,23927,400,1,0,0,0,36
5079,47,28980,400,0,0,0,0,36
5100,42,26199,400,1,0,0,0,36
...,...,...,...,...,...,...,...,...
5529,44,0,400,2,1,0,0,36
5531,33,0,341,0,1,0,0,36
5532,38,0,333,2,1,0,0,36
5564,58,20684,400,1,0,0,0,36
5688,49,28240,400,2,0,0,0,36

In [30]:
df

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,632304,36
1,40,69517,781,1,1,0,417102,36
2,49,28572,568,2,0,0,83408,36
3,60,71067,654,1,1,1,284268,36
4,39,68930,767,1,1,0,482510,36
...,...,...,...,...,...,...,...,...
5791,36,27884,353,1,0,0,139420,36
5792,47,28029,304,0,0,0,112116,36
5793,68,11748,351,1,0,0,35244,36
5794,68,10998,368,2,0,0,32994,36
5795,60,13191,397,2,0,0,52764,36

In [31]:
new_unemp_loans = (df['employed'] == 0) & (df['loan_amount'] == 0) & (df['credit_score'] < 400)

In [32]:
df[new_unemp_loans]

Empty DataFrame
Columns: [age, income, credit_score, existing_loans, employed, default, loan_amount, loan_tenure_months]
Index: []

In [33]:
new_unemp = (df['employed'] == 0) & (df['income'] == 0)

In [34]:

df.loc[(new_unemp) & (df['age'].between(25, 30)), 'income'] = \
    np.random.randint(10000, 18000, size=df[(new_unemp) & (df['age'].between(25, 30))].shape[0])

df.loc[(new_unemp) & (df['age'].between(31, 35)), 'income'] = \
    np.random.randint(15000, 25000, size=df[(new_unemp) & (df['age'].between(31, 35))].shape[0])

df.loc[(new_unemp) & (df['age'].between(36, 45)), 'income'] = \
    np.random.randint(26000, 28000, size=df[(new_unemp) & (df['age'].between(36, 45))].shape[0])

df.loc[(new_unemp) & (df['age'].between(46, 55)), 'income'] = \
    np.random.randint(28000, 30000, size=df[(new_unemp) & (df['age'].between(46, 55))].shape[0])

df.loc[(new_unemp) & (df['age'].between(56, 59)), 'income'] = \
    np.random.randint(20000, 22000, size=df[(new_unemp) & (df['age'].between(56, 59))].shape[0])

df.loc[(new_unemp) & (df['age'] >= 60), 'income'] = \
    np.random.randint(8000, 15000, size=df[(new_unemp) & (df['age'] >= 60)].shape[0])

print(f"Income assigned to {new_unemp.sum()} unemployed rows!")

Income assigned to 0 unemployed rows!

In [35]:
df[new_unemp]

Empty DataFrame
Columns: [age, income, credit_score, existing_loans, employed, default, loan_amount, loan_tenure_months]
Index: []

In [36]:
new_unemp_worst = (df['employed'] == 0) & (df['loan_amount'] == 0) & (df['credit_score'] <= 400)

In [37]:

df.loc[(new_unemp_worst) & (df['age'].between(25, 29)), 'loan_amount'] = \
    df.loc[(new_unemp_worst) & (df['age'].between(25, 29)), 'income'] * np.random.randint(4, 6, size=df[(new_unemp_worst) & (df['age'].between(25, 29))].shape[0])

df.loc[(new_unemp_worst) & (df['age'].between(30, 40)), 'loan_amount'] = \
    df.loc[(new_unemp_worst) & (df['age'].between(30, 40)), 'income'] * np.random.randint(4, 6, size=df[(new_unemp_worst) & (df['age'].between(30, 40))].shape[0])

df.loc[(new_unemp_worst) & (df['age'].between(41, 55)), 'loan_amount'] = \
    df.loc[(new_unemp_worst) & (df['age'].between(41, 55)), 'income'] * np.random.randint(4, 6, size=df[(new_unemp_worst) & (df['age'].between(41, 55))].shape[0])

df.loc[(new_unemp_worst) & (df['age'].between(56, 59)), 'loan_amount'] = \
    df.loc[(new_unemp_worst) & (df['age'].between(56, 59)), 'income'] * np.random.randint(4, 6, size=df[(new_unemp_worst) & (df['age'].between(56, 59))].shape[0])

df.loc[(new_unemp_worst) & (df['age'] >= 60), 'loan_amount'] = \
    df.loc[(new_unemp_worst) & (df['age'] >= 60), 'income'] * np.random.randint(3, 5, size=df[(new_unemp_worst) & (df['age'] >= 60)].shape[0])

df.loc[new_unemp_worst, 'loan_amount'] = df.loc[new_unemp_worst, 'loan_amount'].astype(int)

print(f"Loans assigned to {new_unemp_worst.sum()} unemployed new rows!")

Loans assigned to 10 unemployed new rows!

In [38]:
df[new_unemp_worst]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5002,53,29201,400,3,0,0,116804,36
5024,38,27369,400,2,0,0,136845,36
5044,33,23927,400,1,0,0,119635,36
5079,47,28980,400,0,0,0,144900,36
5100,42,26199,400,1,0,0,104796,36
5134,53,28696,400,3,0,0,114784,36
5193,59,21263,400,1,0,0,106315,36
5245,49,29279,400,2,0,0,117116,36
5564,58,20684,400,1,0,0,103420,36
5688,49,28240,400,2,0,0,141200,36

In [39]:
df.loc[
    (df["employed"]==1) &
    (df["income"]==0) &
    (df["credit_score"].between(300, 400))
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5263,70,0,361,2,1,0,0,36
5264,68,0,341,0,1,0,0,36
5265,43,0,332,2,1,0,500000,36
5266,37,0,325,0,1,0,0,36
5267,45,0,330,2,1,0,500000,36
...,...,...,...,...,...,...,...,...
5528,66,0,392,2,1,0,0,36
5529,44,0,400,2,1,0,0,36
5530,50,0,399,0,1,0,500000,36
5531,33,0,341,0,1,0,0,36
5532,38,0,333,2,1,0,0,36

In [40]:
new_emp_worst = (df['employed'] == 1) & (df['credit_score'].between(300, 400))

In [41]:

df.loc[(new_emp_worst) & (df['age'].between(25, 28)), 'income'] = \
    np.random.randint(20000, 35000, size=df[(new_emp_worst) & (df['age'].between(25, 28))].shape[0])

df.loc[(new_emp_worst) & (df['age'].between(29, 30)), 'income'] = \
    np.random.randint(33000, 40000, size=df[(new_emp_worst) & (df['age'].between(29, 30))].shape[0])

df.loc[(new_emp_worst) & (df['age'].between(31, 35)), 'income'] = \
    np.random.randint(45000, 63000, size=df[(new_emp_worst) & (df['age'].between(31, 35))].shape[0])

df.loc[(new_emp_worst) & (df['age'].between(36, 45)), 'income'] = \
    np.random.randint(65000, 85000, size=df[(new_emp_worst) & (df['age'].between(36, 45))].shape[0])

df.loc[(new_emp_worst) & (df['age'].between(46, 55)), 'income'] = \
    np.random.randint(100000, 180000, size=df[(new_emp_worst) & (df['age'].between(46, 55))].shape[0])

df.loc[(new_emp_worst) & (df['age'].between(56, 59)), 'income'] = \
    np.random.randint(100000, 140000, size=df[(new_emp_worst) & (df['age'].between(56, 59))].shape[0])

df.loc[(new_emp_worst) & (df['age'] >= 60), 'income'] = \
    np.random.randint(70000, 100000, size=df[(new_emp_worst) & (df['age'] >= 60)].shape[0])

print(f"Income assigned to {new_emp_worst.sum()} employed worst credit rows!")

Income assigned to 272 employed worst credit rows!

In [42]:
df[new_emp_worst]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
1507,53,169253,399,3,1,1,545055,36
1561,33,45898,375,1,1,0,214932,36
5263,70,70161,361,2,1,0,0,36
5264,68,83011,341,0,1,0,0,36
5265,43,67892,332,2,1,0,500000,36
...,...,...,...,...,...,...,...,...
5528,66,75870,392,2,1,0,0,36
5529,44,77868,400,2,1,0,0,36
5530,50,114925,399,0,1,0,500000,36
5531,33,47563,341,0,1,0,0,36
5532,38,70170,333,2,1,0,0,36

In [43]:
new_emp_worst_loans = (df['employed'] == 1) & (df['credit_score'].between(300, 400))

In [44]:
new_emp_worst_loans = (df['employed'] == 1) & (df['loan_amount'] == 0) & (df['credit_score'].between(300, 400))

df.loc[(new_emp_worst_loans) & (df['age'].between(25, 29)), 'loan_amount'] = \
    df.loc[(new_emp_worst_loans) & (df['age'].between(25, 29)), 'income'] * np.random.randint(4, 6, size=df[(new_emp_worst_loans) & (df['age'].between(25, 29))].shape[0])

df.loc[(new_emp_worst_loans) & (df['age'].between(30, 40)), 'loan_amount'] = \
    df.loc[(new_emp_worst_loans) & (df['age'].between(30, 40)), 'income'] * np.random.randint(4, 6, size=df[(new_emp_worst_loans) & (df['age'].between(30, 40))].shape[0])

df.loc[(new_emp_worst_loans) & (df['age'].between(41, 55)), 'loan_amount'] = \
    df.loc[(new_emp_worst_loans) & (df['age'].between(41, 55)), 'income'] * np.random.randint(4, 6, size=df[(new_emp_worst_loans) & (df['age'].between(41, 55))].shape[0])

df.loc[(new_emp_worst_loans) & (df['age'].between(56, 59)), 'loan_amount'] = \
    df.loc[(new_emp_worst_loans) & (df['age'].between(56, 59)), 'income'] * np.random.randint(3, 5, size=df[(new_emp_worst_loans) & (df['age'].between(56, 59))].shape[0])

df.loc[(new_emp_worst_loans) & (df['age'] >= 60), 'loan_amount'] = \
    df.loc[(new_emp_worst_loans) & (df['age'] >= 60), 'income'] * np.random.randint(3, 5, size=df[(new_emp_worst_loans) & (df['age'] >= 60)].shape[0])

df.loc[new_emp_worst_loans, 'loan_amount'] = df.loc[new_emp_worst_loans, 'loan_amount'].astype(int)

print(f"Loans assigned to {new_emp_worst_loans.sum()} employed worst credit rows!")

Loans assigned to 190 employed worst credit rows!

In [45]:
df[new_emp_worst_loans]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5263,70,70161,361,2,1,0,280644,36
5264,68,83011,341,0,1,0,332044,36
5266,37,75230,325,0,1,0,300920,36
5269,60,70111,340,1,1,0,210333,36
5271,34,61377,356,3,1,0,306885,36
...,...,...,...,...,...,...,...,...
5527,58,121639,314,0,1,0,364917,36
5528,66,75870,392,2,1,0,227610,36
5529,44,77868,400,2,1,0,389340,36
5531,33,47563,341,0,1,0,190252,36
5532,38,70170,333,2,1,0,280680,36

In [46]:
df.loc[
    (df["loan_amount"]==500000)
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
5265,43,67892,332,2,1,0,500000,36
5267,45,83161,330,2,1,0,500000,36
5268,51,150202,387,0,1,0,500000,36
5270,55,106863,369,3,1,0,500000,36
5276,53,117922,349,3,1,0,500000,36
...,...,...,...,...,...,...,...,...
5516,41,74970,390,3,1,0,500000,36
5519,44,65683,305,1,1,0,500000,36
5521,42,84849,387,2,1,0,500000,36
5524,44,76016,359,3,1,0,500000,36
5530,50,114925,399,0,1,0,500000,36

In [47]:
loan_500k = df['loan_amount'] == 500000

# Income < 100k: normal multiple
df.loc[(loan_500k) & (df['income'] < 100000), 'loan_amount'] = \
    df.loc[(loan_500k) & (df['income'] < 100000), 'income'] * np.random.randint(4, 6, size=df[(loan_500k) & (df['income'] < 100000)].shape[0])

# Income >= 100k: 500k+ with randomness
df.loc[(loan_500k) & (df['income'] >= 100000), 'loan_amount'] = \
    np.random.randint(500000, 800000, size=df[(loan_500k) & (df['income'] >= 100000)].shape[0])

df.loc[loan_500k, 'loan_amount'] = df.loc[loan_500k, 'loan_amount'].astype(int)

print(f"Fixed {loan_500k.sum()} rows with 500k loans!")

Fixed 80 rows with 500k loans!

In [48]:
df

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,632304,36
1,40,69517,781,1,1,0,417102,36
2,49,28572,568,2,0,0,83408,36
3,60,71067,654,1,1,1,284268,36
4,39,68930,767,1,1,0,482510,36
...,...,...,...,...,...,...,...,...
5791,36,27884,353,1,0,0,139420,36
5792,47,28029,304,0,0,0,112116,36
5793,68,11748,351,1,0,0,35244,36
5794,68,10998,368,2,0,0,32994,36
5795,60,13191,397,2,0,0,52764,36

In [49]:
df.loc[
    (df["loan_amount"]>0)
]

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,632304,36
1,40,69517,781,1,1,0,417102,36
2,49,28572,568,2,0,0,83408,36
3,60,71067,654,1,1,1,284268,36
4,39,68930,767,1,1,0,482510,36
...,...,...,...,...,...,...,...,...
5791,36,27884,353,1,0,0,139420,36
5792,47,28029,304,0,0,0,112116,36
5793,68,11748,351,1,0,0,35244,36
5794,68,10998,368,2,0,0,32994,36
5795,60,13191,397,2,0,0,52764,36

In [51]:
df.loc[
    (df["loan_amount"]==0)
]

Empty DataFrame
Columns: [age, income, credit_score, existing_loans, employed, default, loan_amount, loan_tenure_months]
Index: []

In [52]:
df.to_csv("csv-2/copy.csv", index=False)
df.to_csv("csv-2/modified.csv", index=False)