In [1]:
print("Hello World")

Hello World

In [25]:
import pandas as pd
import numpy as np
FILE_PATH = "csv-2/copy.csv"

In [26]:
df = pd.read_csv(FILE_PATH)

In [24]:
df.head()

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,632304,24
1,40,69517,781,1,1,0,417102,12
2,49,28572,568,2,0,0,83408,12
3,60,71067,654,1,1,1,284268,24
4,39,68930,767,1,1,0,482510,12

In [21]:
df.to_csv(FILE_PATH, index=False)

In [27]:
df.head()

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months
0,47,105384,616,1,1,0,632304,24
1,40,69517,781,1,1,0,417102,12
2,49,28572,568,2,0,0,83408,12
3,60,71067,654,1,1,1,284268,24
4,39,68930,767,1,1,0,482510,12

In [29]:
df["existing_loan_emi"] = 0

In [30]:
df

,age,income,credit_score,existing_loans,employed,default,loan_amount,loan_tenure_months,existing_loan_emi
0,47,105384,616,1,1,0,632304,24,0
1,40,69517,781,1,1,0,417102,12,0
2,49,28572,568,2,0,0,83408,12,0
3,60,71067,654,1,1,1,284268,24,0
4,39,68930,767,1,1,0,482510,12,0
...,...,...,...,...,...,...,...,...,...
5791,36,27884,353,1,0,0,139420,36,0
5792,47,28029,304,0,0,0,112116,30,0
5793,68,11748,351,1,0,0,35244,30,0
5794,68,10998,368,2,0,0,32994,30,0
5795,60,13191,397,2,0,0,52764,18,0